<?php

/**
 * Implements hook_views_api().
 */
function xdruple_invoice_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'xdruple_invoice') . '/includes/views',
  );
}

/**
 * Implements hook_init()
 */
function xdruple_invoice_init() {
  module_load_include('inc', 'xdruple_invoice', 'pages/invoice');
}

/**
 * Implements hook_menu()
 */
function xdruple_invoice_menu() {
  $items = array();

  $items['invoice/%'] = array(
    'title'            => 'Invoice',
    'page callback'    => 'xdruple_invoice_page',
    'page arguments'   => array(1),
    'access arguments' => array('access content'),
    'file'             => 'pages/invoice.inc',
    'type'             => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_views_pre_execute().
 */
function xdruple_invoice_views_pre_execute($view) {
  if ($view->name === 'xd_invoices') {
    // Query on Customer.
    if (isset($_SESSION['rescued']['customer'])) {
      $view->query->query->propertyConditions[] = array(
        'column' => 'customer',
        'value' => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
      $view->build_info['count_query']->propertyConditions[] = array(
        'column' => 'customer',
        'value' => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
    }

// TODO: We can't currently query on Ship To because the ORM doesn't expose it.
//     // Query on Ship To.
//     if (isset($_SESSION['rescued']['ship_to'])) {
//       $view->query->query->propertyConditions[] = array(
//         'column' => 'shiptoName',
//         'value' => $_SESSION['rescued']['ship_to'],
//         'operator' => '=',
//       );
//       $view->build_info['count_query']->propertyConditions[] = array(
//         'column' => 'shiptoName',
//         'value' => $_SESSION['rescued']['ship_to'],
//         'operator' => '=',
//       );
//     }
  }
}

/**
 * Implements hook_theme()
 */
function xdruple_invoice_theme() {
  $items = array();

  $items['invoice_page'] = array(
    'variables' => array(
      'invoice' => array(),
    ),
    'template'  => 'theme/invoice-page',
    'file'      => 'theme/theme.inc',
  );

  return $items;
}
