<?php

define('LABEL_INLINE', 'inline');
define('LABEL_ABOVE', 'above');
define('LABEL_HIDDEN', 'hidden');

/**
 * Implements hook_compass_module()
 */
function xdruple_commerce_compass_module() {
  return new \CDD\Compass\DrupalModule('xdruple_commerce', array('xdruple_commerce'));
}

/**
 * Implements hook_user_login().
 */
function xdruple_commerce_user_login(&$edit, $account) {
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    $redirect = variable_get('xdruple_commerce_login_redirect_page', FALSE);
    $frontpage = variable_get('site_frontpage');

    if (!empty($redirect) && !isset($_GET['destination'])) {
      $edit['redirect'] = $redirect;
    } elseif (isset($_GET['destination']) && $frontpage === $_GET['destination']) {
      $_GET['destination'] = $redirect;
      $edit['redirect'] = $redirect;
    }
  }
}

/**
* Implements hook_entity_info_alter().
*
* Override Drupal Commerce's entities to use xTuples.
*/
function xdruple_commerce_entity_info_alter(&$info) {
  // TODO: Get wsclient name. Assuming 'xtuple_' here.

  if (isset($info['xtuple_xdproduct'], $info['commerce_product']) && true) {
    // Cache original to reset some key settings.
    $original = $info['commerce_product'];

    // Override 'api-list-callback' to support exclusive items.
    $info['xtuple_xdproduct']['api-list-callback'] = 'xdruple_commerce_api_customer_exclusive_item_list';

    // TODO: Break the reference: (array)clone(object)$operation_info['xtuple_xdproduct']
    $info['commerce_product'] = $info['xtuple_xdproduct'];
    $info['commerce_product']['entity keys']['bundle'] = 'type';
    $info['commerce_product']['entity keys']['name'] = 'product_id';

    // Preserve some of the original entity_info settings.
    $info['commerce_product']['label'] = $original['label'];
    $info['commerce_product']['bundles']['product'] = $original['bundles']['product'];
    $info['commerce_product']['view modes'] = $original['view modes'];
    $info['commerce_product']['uri callback'] = $original['uri callback'];
    $info['commerce_product']['access callback'] = $original['access callback'];
  }
}

/**
 * Implements hook_entity_operation_info_alter(().
 *
 * Override Drupal Commerce's entities to use the RESCUED entity operation handler.
 *
 * @param $operation_info
 *  The array of data provided by hook_entity_operation_info().
 */
function xdruple_commerce_entity_operation_info_alter(&$operation_info) {
  // TODO: Consider removing 'operations ui' from commerce_product in
  // xdruple_commerce_entity_info_alter() instead of adding this here.

  // Add a handler for commerce_product.
  if (isset($operation_info['xtuple_xdproduct'])) {
    // TODO: Break the reference: (array)clone(object)$operation_info['xtuple_xdproduct']
    $operation_info['commerce_product'] = $operation_info['xtuple_xdproduct'];
  }

  // Add a handler for commerce_customer_profile.
//   if (isset($operation_info['xtuple_xdcustomerrelationprofile'])) {
//     // TODO: Break the reference: (array)clone(object)$operation_info['xtuple_xdcustomerrelationprofile']
//     $operation_info['commerce_customer_profile'] = $operation_info['xtuple_xdcustomerrelationprofile'];
//   }
}

/**
 * Implements hook_menu_alter().
 *
 * Wrap any 'access checkout' or 'access content' items in our custom callback
 * so we can dynamically grant it.
 */
function xdruple_commerce_menu_alter(&$items) {
  if (!empty($items['checkout'])) {
    array_unshift(
      $items['checkout']['access arguments'],
      'checkout',
      'create'
    );
    $items['checkout']['access callback'] = 'xdruple_access';
  }
  if (!empty($items['checkout/%commerce_order'])) {
    array_unshift(
      $items['checkout/%commerce_order']['access arguments'],
      'checkout/%commerce_order',
      'update'
    );
    $items['checkout/%commerce_order']['access callback'] = 'xdruple_access';
  }
  if (!empty($items['checkout/%commerce_order/%commerce_checkout_page'])) {
    array_unshift(
      $items['checkout/%commerce_order/%commerce_checkout_page']['access arguments'],
      'checkout/%commerce_order/%commerce_checkout_page',
      'update'
    );
    $items['checkout/%commerce_order/%commerce_checkout_page']['access callback'] = 'xdruple_access';
  }
  if (!empty($items['cart'])) {
    array_unshift(
      $items['cart']['access arguments'],
      'cart',
      'update'
    );
    $items['cart']['access callback'] = 'xdruple_access';
  }
  if (!empty($items['cart/my'])) {
    array_unshift(
      $items['cart/my']['access arguments'],
      'cart/my',
      'update'
    );
    $items['cart/my']['access callback'] = 'xdruple_access';
  }
}

/**
 * Implements hook_commerce_line_item_summary_link_info_alter().
 *
 * Wrap any 'access checkout' items in 'access xtuple checkout' so we can
 * dynamically grant it.
 */
function xdruple_commerce_commerce_line_item_summary_link_info_alter(&$links) {
  if (!empty($links['checkout'])) {
    $links['checkout']['access'] = xdruple_access(
      'commerce_line_item_summary_link_info',
      'view',
      'access checkout'
    );
  }
}

/**
 * Implements hook_rescued_register_clients_resources_alter().
 */
function xdruple_commerce_rescued_register_clients_resources_alter(&$rescued_clients_url_resources) {
  if (!in_array('XdCustomerRelation', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'XdCustomerRelation';
  }
  if (!in_array('Customer', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'Customer';
  }
  if (!in_array('XdCustomer', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'XdCustomer';
  }
  if (!in_array('XdProduct', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'XdProduct';
  }
  if (!in_array('XdCatalog', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'XdCatalog';
  }
  if (!in_array('XdCatalogGroup', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'XdCatalogGroup';
  }
  if (!in_array('SalesOrder', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'SalesOrder';
  }

  return $rescued_clients_url_resources;
}

/**
 * Implements hook_cpanel_alter()
 */
function xdruple_commerce_cpanel_alter(&$form, &$form_state) {
  if (empty($form['xdruple_commerce_store_settings'])) {
    $form['xdruple_commerce_store_settings'] = array(
      '#type'  => 'fieldset',
      '#title' => t('Store settings'),
      '#group' => 'system_settings',
    );
  }

  $form['xdruple_commerce_store_settings']['xdruple_commerce_filter_exclusive_items'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Filter Product Lists against Customer Exclusive Items'),
    '#description'   => t('When checked, all product lists are ran through the ' .
                          'Customer Exclusive Items filter. This will restrict ' .
                          'Product Lists to only those products a Customer is ' .
                          'allowed to see based on their Pricing Schedules and ' .
                          'the Exclusive Item flag set on an Item master. If ' .
                          'you want to hide Exclusive Items from some Customers ' .
                          ', you will need to check this box. '),
    '#default_value' => variable_get('xdruple_commerce_filter_exclusive_items', FALSE),
  );

  $sites = xdruple_fields_get_site_list();
  if (count($sites) === 1) {
    variable_set('xdruple_commerce_default_warehouse', array_shift(array_keys($sites)));
  } else if (count($sites) > 1) {
    $form['xdruple_commerce_store_settings']['xdruple_commerce_default_warehouse'] = array(
      '#type'          => 'select',
      '#options'       => $sites,
      '#default_value' => variable_get('xdruple_commerce_default_warehouse', '- None -'),
      '#empty_option'  => '- None -',
      '#title'         => t('Default Warehouse/Site'),
      '#description'   => t("The default Warehouse/Site to use when none is set on a Customer's master in xTuple"),
      '#required'      => true,
    );
  } else {
    drupal_set_message(t('Cannot find any Warehouse/Sites to set as default. Please contact the website administrator.'), 'warning');
  }

  $form['xdruple_commerce_store_settings']['xdruple_commerce_default_warehouse_access'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Restrict users from changing the Warehouse/Site orders are submitted for.'),
    '#description'   => t('When checked, users will not be able to change the ' .
                          "Warehouse/Site orders are submitted for. The Customer's" .
                          'default warehouse will be used. If no Customer default ' .
                          'is set, the defualt you set here will be used if you ' .
                          'have more than one Warehouse/Site. If you only have one, ' .
                          'it will be the default.'),
    '#default_value' => variable_get('xdruple_commerce_default_warehouse_access', FALSE),
  );

  $form['xdruple_commerce_store_settings']['xdruple_commerce_login_redirect_page'] = array(
    '#type'          => 'textfield',
    '#size'          => 60,
    '#title'         => t('Redirect after log in'),
    '#description'   => t('Redirect user to a certain page after logging in to the site. ' .
                          'When filled out, users will be redirected to the path ' .
                          'you enter here. e.g. node/123 For the home page, enter: &lt;front&gt;'),
    '#default_value' => variable_get('xdruple_commerce_login_redirect_page', FALSE),
  );
}

/**
 * Implements hook_rescued_operation_entityform_alter().
 */
function xdruple_commerce_rescued_operation_entityform_alter(&$form, &$form_state, $context) {
  $form_id = $form_state['build_info']['form_id'];

  /** @var Xtuple\Xdruple\Session\RescuedSession $session */
  $session = extensions_get_session();

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdstdordproduct') {
    // Default this form to the customer and ship to in the user's session.
    if ($session->getRescued('customer')) {
      $customer = $session->getRescued('customer');
      $form['customer']['#default_value'] = $customer;
      $form['customer']['#options'] = array($customer => $customer);
    } else {
      $customer = null;
    }
    if ($session->getRescued('ship_to')) {
      $form['shipto']['#default_value'] = $session->getRescued('ship_to');
      $form['shipto']['#options'] = xdruple_fields_get_ship_to_list($customer);
    }
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdusercontact') {
    // Modify this entity form to hide some properties/fields.
    if (!user_access('administer users')) {
      $form['create_new_customer']['#type'] = 'hidden';
      $form['create_new_customer']['#attributes']['disabled'] = TRUE;
      $form['create_new_customer']['#default_value'] = TRUE;

      $form['create_xtuple_user_association']['#type'] = 'hidden';
      $form['create_xtuple_user_association']['#attributes']['disabled'] = TRUE;
      $form['create_xtuple_user_association']['#default_value'] = TRUE;
    } else {
      $form['create_new_customer']['#title'] = 'Create new xTuple Customer';
      $form['create_new_customer']['#description'] = 'Check this box to create an xTuple Customer for this user. If this is not checked, this user may not be able to place orders.';
      $form['create_new_customer']['#default_value'] = !isset($context['entity']->is_new) ? $context['entity']->create_new_customer : TRUE;

      if (isset($context['entity']->is_new) && $context['entity']->is_new) {
        $context['entity']->create_new_customer = TRUE;

        if (isset($form_state['input']['xd_contact_association'][LANGUAGE_NONE]['form'])) {
          $form_state['input']['xd_contact_association'][LANGUAGE_NONE]['form']['create_new_customer'] =  true;
        }
      }

      if (!isset($context['entity']->is_new) && $context['entity']->create_new_customer) {
        // Once create_new_customer is set, you can't unset it.
        $form['create_new_customer']['#attributes']['disabled'] = TRUE;
      }
    }
    $form['create_new_customer']['#element_validate'] = array('xdruple_commerce_user_reg_form_validate');

    $form['xdruple_site']['#type'] = 'hidden';
    $form['xdruple_site']['#attributes']['disabled'] = TRUE;
    $form['xdruple_site']['#options'][''] = ' - None - ';
    // We add this below in xdruple_commerce_form_alter().
    $form['xdruple_site']['#required'] = FALSE;
    $form['xdruple_site']['#element_validate'] = array('xdruple_commerce_user_reg_form_validate');

    $form['drupalUserUuid']['#type'] = 'hidden';
    $form['drupalUserUuid']['#attributes']['disabled'] = TRUE;
    $form['drupalUserUuid']['#required'] = FALSE;
    $form['drupalUserUuid']['#default_value'] = isset($context['entity']->drupalUserUuid) ? $context['entity']->drupalUserUuid : xdruple_guidv4();

    unset ($form['uuid']);
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcontact') {
    // Modify this entity form to hide some properties/fields.
    unset ($form['number']);
    unset ($form['honorific']);
    unset ($form['middleName']);
    unset ($form['suffix']);
    unset ($form['jobTitle']);
    unset ($form['initials']);
    unset ($form['alternate']);
    unset ($form['fax']);
    unset ($form['webAddress']);

    $form['firstName']['#weight'] = -44;
    $form['lastName']['#weight'] = -43;
    $form['primaryEmail']['#weight'] = -42;
    $form['phone']['#weight'] = -41;

    $form['firstName']['#required'] = true;
    $form['lastName']['#required'] = true;
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdaddress') {
    // Modify this entity form to hide some properties/fields.
    unset ($form['number']);

    $form['country']['#weight'] = -47;
    $form['line1']['#weight'] = -46;
    $form['line2']['#weight'] = -45;
    $form['line3']['#weight'] = -44;
    $form['city']['#weight'] = -43;
    $form['state']['#weight'] = -42;
    $form['postalCode']['#weight'] = -41;

    $countries = _addressfield_country_options_list();
    $xtuple_countries_format = array('' => '--');

    // xTuple xm.xdruple_commerce_address uses a full country name as the key.
    foreach ($countries as $key => $value) {
      $xtuple_countries_format[$value] = $value;
    }

    $format = array();

    if (isset($form_state['triggering_element']) && $form_state['triggering_element']['#name'] === 'country') {
      // For non-IEF
      $country = drupal_array_get_nested_value($form_state['values'], $form_state['triggering_element']['#parents']);
      $selected_country = array_search($country, $countries);
    } else {
      // For initial load an IEF ajax refreshes.
      $selected_country = isset($context['entity']->country) ? array_search($context['entity']->country, $countries) : '';
    }
    $address = array(
      'country' => $selected_country,
    );
    $addr_context = array(
      'mode' => 'form',
    );

    module_load_include('inc', 'addressfield', 'plugins/format/address');
    addressfield_format_address_generate($format, $address, $addr_context);

    if (isset($form['#parents'])) {
      $wrapper_id = 'xtuple-address-wrapper-' . implode('-', $form['#parents']);
    } else {
      $wrapper_id = 'xtuple-address-wrapper';
    }
    $form['#wrapper_id'] = $wrapper_id;
    $form['#prefix'] = '<div id="' . $wrapper_id . '">';
    $form['#suffix'] = '</div>';

    // If this is a child IEF and the operation is 'add', we can't make any of
    // the address fields required becuase we allow contacts to be saved with
    // no address set. There are also use cases like Customer that has a
    // Correspondence Contact that can be blank. Skip for user reg/profile
    // forms because it should be required on those.
    $skip_required = false;
    if (isset($form['#ief_id'], $form['#op']) && $form_id !== 'user_register_form' && $form_id !== 'user_profile_form') {
      $path_parts = explode('--', $form['#ief_id']);

      if ((count($path_parts) > 1 && $form['#op'] === 'add')) {
        $skip_required = true;
      } elseif (isset($form_state['values'])) {
        $country_parents = $form['#parents'];
        $country_parents[] = 'country';
        $country = drupal_array_get_nested_value($form_state['values'], $country_parents);

        if (empty($country) && drupal_array_get_nested_value($form_state['values'], $form['#parents'])) {
          $skip_required = true;
        }
      }
    }

    $form['country']['#type'] = 'select';
    $form['country']['#options'] = $xtuple_countries_format;
    $form['country']['#weight'] = -47;
    $form['country']['#default_value'] = isset($context['entity']->country) ? $context['entity']->country : '';
    $form['country']['#title'] = $format['country']['#title'];
    $form['country']['#required'] = $skip_required ? false : $format['country']['#required'];
    $form['country']['#ajax']['callback'] = 'addressfield_standard_widget_refresh';
    $form['country']['#ajax']['wrapper'] = $wrapper_id;
    $form['country']['#ief_processing'] = false; // Do not want to save this through IEF on an ajax update.


    $form['line1']['#title'] = $format['street_block']['thoroughfare']['#title'];
    $form['line1']['#size'] = $format['street_block']['thoroughfare']['#size'];
    $form['line1']['#required'] = $skip_required ? false : $format['street_block']['thoroughfare']['#required'];

    $form['line2']['#title'] = $format['street_block']['premise']['#title'];
    $form['line2']['#size'] = $format['street_block']['premise']['#size'];


    $form['line3']['#title'] = 'Address 3';
    $form['line3']['#size'] = $format['street_block']['premise']['#size'];


    $form['city']['#title'] = $format['locality_block']['locality']['#title'];
    $form['city']['#size'] = $format['locality_block']['locality']['#size'];
    $form['city']['#required'] = $skip_required ? false : $format['locality_block']['locality']['#required'];


    if (isset($format['locality_block']['administrative_area'])) {
      if (isset($format['locality_block']['administrative_area']['#options'])) {
        $form['state']['#type'] = 'select';
        $form['state']['#options'] = $format['locality_block']['administrative_area']['#options'];
      } else {
        $form['state']['#type'] = 'textfield';
        $form['state']['#size'] = $format['locality_block']['administrative_area']['#size'];
      }
      $form['state']['#title'] = $format['locality_block']['administrative_area']['#title'];
      $form['state']['#default_value'] = isset($context['entity']->state) ? $context['entity']->state : '_none';
      $form['state']['#required'] = $skip_required ? false : $format['locality_block']['administrative_area']['#required'];
    } else {
      unset($form['state']);
    }

    if (isset($format['locality_block']['postal_code'])) {
      $form['postalCode']['#title'] = $format['locality_block']['postal_code']['#title'];
      $form['postalCode']['#size'] = $format['locality_block']['postal_code']['#size'];
      $form['postalCode']['#required'] = $skip_required ? false : $format['locality_block']['postal_code']['#required'];
    } else {
      unset($form['postalCode']);
    }
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdshipto') {
    // Modify this entity form to hide some properties/fields.
    unset ($form['uuid']);

    $form['number']['#weight'] = -44;
    $form['name']['#weight'] = -43;
    $form['isDefault']['#weight'] = -42;
    $form['customer']['#weight'] = -41;
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcustomerrelation') {
    // Modify this entity form to hide some properties/fields.
    unset ($form['isActive']);

    $form['number']['#weight'] = -42;
    $form['name']['#weight'] = -41;
  }

  if (isset($context['entity_type']) &&
    ($context['entity_type'] === 'commerce_product' || $context['entity_type'] === 'XdProduct' || $context['entity_type'] === 'xtuple_xdproduct')) {

    // Make 'weightUnit' read only.
    $form['weightUnit']['#attributes']['disabled'] = TRUE;
    $description = t("This field is derived from xTuple's Setup->Products->Units Of Measure with the 'Item Weight' flag set. It cannot be changed here.");
    $form['weightUnit']['#description'] = $description;
    // Make 'uomRatio' read only.
    $form['uomRatio']['#attributes']['disabled'] = TRUE;
    $description = t("This field is derived from xTuple's Units Of Measure Ratios. It cannot be changed here.");
    $form['uomRatio']['#description'] = $description;
  }
}

function xdruple_commerce_user_association_callback(&$form, &$form_state) {
  $create_association = false;
  if (isset($form_state['values']['create_xtuple_user_association'])) {
    $create_association = $form_state['values']['create_xtuple_user_association'];
  }

  $ief_key = $form['xd_contact_association'][LANGUAGE_NONE]['#ief_id'];

  if (!$create_association) {
    foreach ($form_state['inline_entity_form'] as $ief_id => $ief) {
      $length = strlen($ief_key);
      if (substr($ief_id, 0, $length) === $ief_key) {
        unset($form_state['inline_entity_form'][$ief_id]);
      }
    }

    unset($form['xd_contact_association'][LANGUAGE_NONE]);
    unset($form_state['complete form']['xd_contact_association'][LANGUAGE_NONE]);
    unset($form_state['input']['xd_contact_association']);
    unset($form_state['values']['xd_contact_association']);
  }

  return $form['xd_contact_association'];
}

/**
 * Implements hook_rescued_entity_default_label_alter().
 */
function xdruple_commerce_rescued_entity_default_label_alter($entity, &$label, $context) {
  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcontact') {
    if (isset($entity->firstName) || isset($entity->lastName)) {
      $label = '';
      $label .= isset($entity->firstName) ? ' ' . $entity->firstName : '';
      $label .= isset($entity->lastName) ? ' ' . $entity->lastName : '';
    }
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdaddress') {
    $label = $entity->line1;
    $label .= ' ' . $entity->city;
    $label .= isset($entity->state) ? ', ' . $entity->state : '';
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdshipto') {
    $label = $entity->number;
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcustomerrelation') {
    $label = $entity->number;
  }
}

/**
 * Implements hook_rescued_entity_build_content_view_alter().
 */
function xdruple_commerce_rescued_entity_build_content_view_alter($entity, &$resource_schema, $context) {
  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcontact') {
    // TODO: Convert this to a function call that has a hook to override.
    // Use that function in xdruple_commerce_rescued_operation_entityform_alter().
    $properity_white_list = array(
      'firstName' => true,
      'lastName' => true,
      'phone' => true,
      'primaryEmail' => true,
      'address' => true,
    );

    // Limit the schema to only the fields we want to display.
    $resource_schema = array_intersect_key($resource_schema, $properity_white_list);
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdaddress') {
    // TODO: Convert this to a function call that has a hook to override.
    // Use that function in xdruple_commerce_rescued_operation_entityform_alter().
    $properity_white_list = array(
      'line1' => true,
      'line2' => true,
      'line3' => true,
      'city' => true,
      'state' => true,
      'postalCode' => true,
      'country' => true,
    );

    // Limit the schema to only the fields we want to display.
    $resource_schema = array_intersect_key($resource_schema, $properity_white_list);
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdshipto') {
    // TODO: Convert this to a function call that has a hook to override.
    // Use that function in xdruple_commerce_rescued_operation_entityform_alter().
    $properity_white_list = array(
      'number' => true,
      'name' => true,
      'isDefault' => true,
      'customer' => true,
      'contact' => true,
      'address' => true,
    );

    // Limit the schema to only the fields we want to display.
    $resource_schema = array_intersect_key($resource_schema, $properity_white_list);
  }

  if (isset($context['entity_type']) && $context['entity_type'] === 'xtuple_xdcustomerrelation') {
    // TODO: Convert this to a function call that has a hook to override.
    // Use that function in xdruple_commerce_rescued_operation_entityform_alter().
    $properity_white_list = array(
      'number' => true,
      'name' => true,
      'billingContact' => true,
      'correspondenceContact' => true,
      'shiptos' => true,
    );

    // Limit the schema to only the fields we want to display.
    $resource_schema = array_intersect_key($resource_schema, $properity_white_list);
  }
}

/**
 * Implements hook_entity_view().
 */
function xdruple_commerce_entity_view($entity, $entity_type, $view_mode, $langcode) {
  if ($entity_type === 'xtuple_xdcontact') {
    // Reset the weights to the correct order.
    $entity->content['firstName']['#weight'] = -4;
    $entity->content['lastName']['#weight'] = -3;
    $entity->content['primaryEmail']['#weight'] = -2;
    $entity->content['phone']['#weight'] = -1;

    // Unset the address and use the 'erp_xdcontactaddress' field instead.
    unset($entity->content['address']);
  }

  if ($entity_type === 'xtuple_xdaddress') {
    // Reset the weights to the correct order and change the labels.
    // For some reason these weights are not respected.  See the
    // xdruple_commerce_field_extra_fields_alter() function.
    $entity->content['line1']['#weight'] = -7;
    $entity->content['line1']['#title'] = 'Address 1';
    $entity->content['line2']['#weight'] = -6;
    $entity->content['line2']['#title'] = 'Address 2';
    $entity->content['line3']['#weight'] = -5;
    $entity->content['line3']['#title'] = 'Address 3';
    $entity->content['city']['#weight'] = -4;
    $entity->content['state']['#weight'] = -3;
    $entity->content['postalCode']['#weight'] = -2;
    $entity->content['country']['#weight'] = -1;
  }

  if ($entity_type === 'xtuple_xdshipto') {
    $entity->content['erp_xdshiptocontact']['#formatter'] = 'entityreference_entity_view';
    // Reset the weights to the correct order.
    $entity->content['number']['#weight'] = -4;
    $entity->content['name']['#weight'] = -3;
    $entity->content['isDefault']['#weight'] = -2;
    $entity->content['customer']['#weight'] = -1;

    // Unset the address and contact. Use the 'erp_xdshiptoxxx' fields instead.
    unset($entity->content['address']);
    unset($entity->content['contact']);

    // Unset the Ship To Email Addresses. It's for internal use only and doesn't need to be displayed.
    unset($entity->content['erp_xdshiptoshiptoemails']);
  }

  if ($entity_type === 'xtuple_xdcustomerrelation') {
    // Reset the weights to the correct order.
    $entity->content['number']['#weight'] = -2;
    $entity->content['name']['#weight'] = -1;

    // Unset some things. Use the 'erp_xdshiptoxxx' fields instead.
    unset($entity->content['isActive']);
    unset($entity->content['billingContact']);
    unset($entity->content['correspondenceContact']);
    unset($entity->content['shiptos']);
  }
}

/**
 * Implements hook_entity_property_info_alter()
 *
 * Add our custom xTuple properties.
 *
 * @param array $info The associative array of entity properties.
 */
function xdruple_commerce_entity_property_info_alter(&$info) {
  if (isset($info['xtuple_xdproduct'], $info['xtuple_xdproduct']['properties'], $info['commerce_product'])) {
    foreach ($info['xtuple_xdproduct']['properties'] as $prop_name => $prop_value) {
      if (!isset($info['commerce_product']['properties'][$prop_name])) {
        // Set product property to match xTuple's entity.
        // TODO: Break the reference: (array)clone(object)$prop_value
        $info['commerce_product']['properties'][$prop_name] = $prop_value;
      }
    }
  }

  if (isset($info['commerce_order'], $info['commerce_order']['properties'])) {
    if (isset($info['commerce_order']['properties']['mail']['validation callback'])) {
      // Change this validation callback to our own that support mulitple emails on one line.
      $info['commerce_order']['properties']['mail']['validation callback'] = 'xdruple_valid_multiple_email_address';
    }
  }
}

/**
 * Implements hook_field_extra_fields_alter()
 *
 * Expose our custom xTuple properties as fields.
 *
 * @param array $info The associative array of 'pseudo-field' components.
 */
function xdruple_commerce_field_extra_fields_alter(&$info) {
  if (isset($info['xtuple_xdproduct'],
    $info['xtuple_xdproduct']['xtuple_xdproduct'],
    $info['commerce_product'],
    $info['commerce_product']['product'])) {

    foreach ($info['xtuple_xdproduct']['xtuple_xdproduct'] as $view_name => $view_fields) {
      if (isset($info['commerce_product']['product'][$view_name])) {
        foreach ($view_fields as $field_name => $field_values) {
          if (!isset($info['commerce_product']['product'][$view_name][$field_name])) {
            // Set product fields to match xTuple's entity.
            // TODO: Break the reference: (array)clone(object)$field_values
            $info['commerce_product']['product'][$view_name][$field_name] = $field_values;
          }
        }
      }
    }
  }

  if (isset($info['xtuple_xdcontact'])) {
    $contact_fields = &$info['xtuple_xdcontact']['xtuple_xdcontact'];

    $contact_fields['display']['firstName']['weight'] = -54;
    $contact_fields['display']['lastName']['weight'] = -53;
    $contact_fields['display']['primaryEmail']['weight'] = -52;
    $contact_fields['display']['phone']['weight'] = -51;

    $contact_fields['form']['firstName']['weight'] = -44;
    $contact_fields['form']['lastName']['weight'] = -43;
    $contact_fields['form']['primaryEmail']['weight'] = -42;
    $contact_fields['form']['phone']['weight'] = -41;
  }

  if (isset($info['xtuple_xdaddress'])) {
    $address_fields = &$info['xtuple_xdaddress']['xtuple_xdaddress'];

    $address_fields['display']['line1']['weight'] = -57;
    $address_fields['display']['line2']['weight'] = -56;
    $address_fields['display']['line3']['weight'] = -55;
    $address_fields['display']['city']['weight'] = -54;
    $address_fields['display']['state']['weight'] = -53;
    $address_fields['display']['postalCode']['weight'] = -52;
    $address_fields['display']['country']['weight'] = -51;

    $address_fields['form']['country']['weight'] = -47;
    $address_fields['form']['line1']['weight'] = -46;
    $address_fields['form']['line2']['weight'] = -45;
    $address_fields['form']['line3']['weight'] = -44;
    $address_fields['form']['city']['weight'] = -43;
    $address_fields['form']['state']['weight'] = -42;
    $address_fields['form']['postalCode']['weight'] = -41;
  }

  if (isset($info['xtuple_xdshipto'])) {
    $shipto_fields = &$info['xtuple_xdshipto']['xtuple_xdshipto'];

    $shipto_fields['display']['number']['weight'] = -54;
    $shipto_fields['display']['name']['weight'] = -53;
    $shipto_fields['display']['isDefault']['weight'] = -52;
    $shipto_fields['display']['customer']['weight'] = -51;

    $shipto_fields['form']['number']['weight'] = -44;
    $shipto_fields['form']['name']['weight'] = -43;
    $shipto_fields['form']['isDefault']['weight'] = -42;
    $shipto_fields['form']['customer']['weight'] = -41;
  }

  if (isset($info['xtuple_xdcustomerrelation'])) {
    $shipto_fields = &$info['xtuple_xdcustomerrelation']['xtuple_xdcustomerrelation'];

    $shipto_fields['display']['number']['weight'] = -52;
    $shipto_fields['display']['name']['weight'] = -51;

    $shipto_fields['form']['number']['weight'] = -42;
    $shipto_fields['form']['name']['weight'] = -41;
  }
}

/**
 * Lets modules add extra fields to product entities without using
 * hook_field_extra_field_alter because of how product_reference calls
 * commerce_product_field_extra_fields() directly instead of using
 * field_info_extra_fields().
 *
 * @See: commerce_product_reference_field_extra_fields()
 *
 * @param $extra
 *   Extra fields from commerce_product_field_extra_fields()
 *
 * @return
 *   Modified extra fields array with your additions/changes.
 */
function xdruple_commerce_commerce_product_add_extra_fields_alter(&$extra) {
  // Modify $extra here to add the extra xTuple specific entity properties.

  foreach (commerce_product_types() as $type => $product_type) {
    $form = array(
      'subTitle' => array(
        'label' => t('Product Sub-Title'),
        'description' => t('Product module sub-title form element'),
        'weight' => -4,
      ),
      'productWeight' => array(
        'label' => t('Product Weight'),
        'description' => t('Product module product weight form element'),
        'weight' => -4,
      ),
      'packageWeight' => array(
        'label' => t('Package Weight'),
        'description' => t('Product module package weight form element'),
        'weight' => -4,
      ),
      'prodLength' => array(
        'label' => t('Length'),
        'description' => t('Product module length form element'),
        'weight' => -4,
      ),
      'prodWidth' => array(
        'label' => t('Width'),
        'description' => t('Product module width form element'),
        'weight' => -4,
      ),
      'prodHeight' => array(
        'label' => t('Height'),
        'description' => t('Product module height form element'),
        'weight' => -4,
      ),
      'packLength' => array(
        'label' => t('Package Length'),
        'description' => t('Product module package length form element'),
        'weight' => -4,
      ),
      'packWidth' => array(
        'label' => t('Package Width'),
        'description' => t('Product module package width form element'),
        'weight' => -4,
      ),
      'packHeight' => array(
        'label' => t('Package Height'),
        'description' => t('Product module package height form element'),
        'weight' => -4,
      ),
      'classCode' => array(
        'label' => t('Class Code'),
        'description' => t('Product module class code form element'),
        'weight' => -4,
      ),
      'productCategory' => array(
        'label' => t('Product Category'),
        'description' => t('Product module product category form element'),
        'weight' => -4,
      ),
      'inventoryUnit' => array(
        'label' => t('Inventory Unit'),
        'description' => t('Product module inventory unit form element'),
        'weight' => -4,
      ),
      'priceUnit' => array(
        'label' => t('Price Unit'),
        'description' => t('Product module price unit form element'),
        'weight' => -4,
      ),
      'uomRatio' => array(
        'label' => t('UOM Ratio'),
        'description' => t('Product module UOM ratio form element'),
        'weight' => -4,
      ),
      'weightUnit' => array(
        'label' => t('Weight Unit'),
        'description' => t('Product module weight unit form element'),
        'weight' => -4,
      ),
      'dimensionUnit' => array(
        'label' => t('Dimension Unit'),
        'description' => t('Product module dimension unit form element'),
        'weight' => -4,
      ),
      'physicalProdUnit' => array(
        'label' => t('Product Dimensions Unit'),
        'description' => t('Product module product dimensions unit form element'),
        'weight' => -4,
      ),
      'physicalPackUnit' => array(
        'label' => t('Package Dimensions Unit'),
        'description' => t('Product module package dimensions unit form element'),
        'weight' => -4,
      ),
      'notes' => array(
        'label' => t('Notes'),
        'description' => t('Product module notes form element'),
        'weight' => -3,
      ),
      'extDescrip' => array(
        'label' => t('Extended Description'),
        'description' => t('Product module extended description form element'),
        'weight' => -3,
      ),
      'urls' => array(
        'label' => t('URLs'),
        'description' => t('Product file URLs'),
        'weight' => -3,
      ),
    );

    $display = array(
      'subTitle' => array(
        'label' => t('Product Sub-Title'),
        'description' => t('Product sub-title'),
        'theme' => 'xdruple_commerce_sub_title',
        'weight' => -4,
      ),
      'productWeight' => array(
        'label' => t('Product Weight'),
        'description' => t('Weight of the product'),
        'theme' => 'xdruple_commerce_product_weight',
        'weight' => -4,
      ),
      'packageWeight' => array(
        'label' => t('Package Weight'),
        'description' => t('Weight of the empty package this product comes in'),
        'theme' => 'xdruple_commerce_package_weight',
        'weight' => -4,
      ),
      'prodLength' => array(
        'label' => t('Length'),
        'description' => t('Product module length form element'),
        'theme' => 'xdruple_commerce_length',
        'weight' => -4,
      ),
      'prodWidth' => array(
        'label' => t('Width'),
        'description' => t('Product module width form element'),
        'theme' => 'xdruple_commerce_width',
        'weight' => -4,
      ),
      'prodHeight' => array(
        'label' => t('Height'),
        'description' => t('Product module height form element'),
        'theme' => 'xdruple_commerce_height',
        'weight' => -4,
      ),
      'packLength' => array(
        'label' => t('Package Length'),
        'description' => t('Product module package length form element'),
        'theme' => 'xdruple_commerce_pack_length',
        'weight' => -4,
      ),
      'packWidth' => array(
        'label' => t('Package Width'),
        'description' => t('Product module package width form element'),
        'theme' => 'xdruple_commerce_pack_width',
        'weight' => -4,
      ),
      'packHeight' => array(
        'label' => t('Package Height'),
        'description' => t('Product module package height form element'),
        'theme' => 'xdruple_commerce_pack_height',
        'weight' => -4,
      ),
      'classCode' => array(
        'label' => t('Class Code'),
        'description' => t('Class Code the product belongs to'),
        'theme' => 'xdruple_commerce_class_code',
        'weight' => -4,
      ),
      'productCategory' => array(
        'label' => t('Product Category'),
        'description' => t('Product Category the product belongs to'),
        'theme' => 'xdruple_commerce_product_category',
        'weight' => -4,
      ),
      'inventoryUnit' => array(
        'label' => t('Inventory Unit'),
        'description' => t('Unit of measure used for inventory'),
        'theme' => 'xdruple_commerce_inventory_unit',
        'weight' => -4,
      ),
      'priceUnit' => array(
        'label' => t('Price Unit'),
        'description' => t('Unit of measure used for the price calculation'),
        'theme' => 'xdruple_commerce_price_unit',
        'weight' => -4,
      ),
      'uomRatio' => array(
        'label' => t('UOM Ratio'),
        'description' => t('Unit of measure ratio between price and inventory'),
        'theme' => 'xdruple_commerce_uom_ratio',
        'weight' => -4,
      ),
      'weightUnit' => array(
        'label' => t('Weight Unit'),
        'description' => t('Unit of measure used for the weight calculation'),
        'theme' => 'xdruple_commerce_weight_unit',
        'weight' => -4,
      ),
      'dimensionUnit' => array(
        'label' => t('Dimension Unit'),
        'description' => t('Product module dimension unit form element'),
        'theme' => 'xdruple_commerce_dimension_unit',
        'weight' => -4,
      ),
      'physicalProdUnit' => array(
        'label' => t('Product Dimensions Unit'),
        'description' => t('Product module product dimensions unit form element'),
        'weight' => -4,
      ),
      'physicalPackUnit' => array(
        'label' => t('Package Dimensions Unit'),
        'description' => t('Product module package dimensions unit form element'),
        'weight' => -4,
      ),
      'notes' => array(
        'label' => t('Notes'),
        'description' => t('Additional notes for the product'),
        'theme' => 'xdruple_commerce_notes',
        'weight' => -3,
      ),
      'extDescrip' => array(
        'label' => t('Extended Description'),
        'description' => t('Extended description of the product'),
        'theme' => 'xdruple_commerce_ex_descrip',
        'weight' => -3,
      ),
      'urls' => array(
        'label' => t('URLs'),
        'description' => t('Product file URLs'),
        'weight' => -3,
      ),
    );

    $extra['commerce_product'][$type]['form'] = array_merge($extra['commerce_product'][$type]['form'], $form);
    $extra['commerce_product'][$type]['display'] = array_merge($extra['commerce_product'][$type]['display'], $display);
  }

  return $extra;
}

/**
 * Implements hook_form_alter()
 *
 * Resolve a problem with undefined commerce_checkout_form on AJAX calls
 * when using page_manager_existing_pages.
 *
 * @See: https://drupal.org/node/1773674
 * @See: https://drupal.org/node/1774770
 * @See: https://drupal.org/node/2134023
 */
function xdruple_commerce_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'commerce_checkout_form') !== false) {
    // Drupal has an automatic dependencies load when a menu item at hook_menu
    // declares an include file where the page callback is located. E.x.
    // $items['checkout/%commerce_order'] = array(
    //  'title' => 'Checkout',
    //  'page callback' => 'commerce_checkout_router',
    //  'page arguments' => array(1),
    //  'access arguments' => array('access checkout'),
    //  'type' => MENU_CALLBACK,
    //  'file' => 'includes/commerce_checkout.pages.inc',
    // );
    // The FAPI store the path of the of an include in the cached $form_state
    // form to satisfy the dependency when for an element in a viewed page
    // has an AJAX behavior so when an AJAX call is received the function
    // form_get_cache look into $form_state['build_info']['files'] and do a
    // include of that specified file. Unfortunately at doing menu_alter of this
    // menu item:
    // $items['checkout/%commerce_order/%commerce_checkout_page']['file'] = $task['file'];
    // The FAPI will include only the file referenced in the menu array and the
    // AJAX call will be broken. We resolve this altering the form to explicit
    // attach the commerce_checkout.pages.inc into the build_info files.

    $form_state['build_info']['files']['commerce_checkout'] = array(
      'module' => 'commerce_checkout',
      'name' => 'includes/commerce_checkout.pages',
      'type' => 'inc',
    );
  }

  // Modify the user registration form to work with xTuple.
  if ($form_id === 'user_register_form' || $form_id === 'user_profile_form') {
    $wrapper_id = 'xd_contact_association_wrapper';
    $form['xd_contact_association']['#wrapper_id'] = $wrapper_id;
    $form['xd_contact_association']['#prefix'] = '<div id="' . $wrapper_id . '">';
    $form['xd_contact_association']['#suffix'] = '</div>';

    $form['create_xtuple_user_association'] = array(
      '#type' => 'checkbox',
      '#title' => 'Create xTuple User Association',
      '#description' => 'Check this box to create an xTuple Contact Association for this user. If this is not checked, this user will not be able to place orders.',
      '#default_value' => TRUE,
      '#required' => FALSE,
      '#weight' => 6,
      '#ajax' => array(
        'callback' => 'xdruple_commerce_user_association_callback',
        'wrapper' => $wrapper_id,
      ),
      '#limit_validation_errors' => array(),
    );

    if (!user_access('administer users')) {
      $form['create_xtuple_user_association']['#type'] = 'hidden';
      $form['create_xtuple_user_association']['#attributes']['disabled'] = TRUE;
      $form['create_xtuple_user_association']['#default_value'] = TRUE;
    }

    if (isset($form['xd_contact_association'][LANGUAGE_NONE]['form']['erp_xdusercontactcontact'][LANGUAGE_NONE]['form']['primaryEmail'])) {
      $contact_form = &$form['xd_contact_association'][LANGUAGE_NONE]['form']['erp_xdusercontactcontact'][LANGUAGE_NONE]['form'];
      $addr_form = &$contact_form['erp_xdcontactaddress'][LANGUAGE_NONE]['form'];

      if (!user_access('administer users')) {
        // Hide the IEF entity_id select list field on the Contact.
        $contact_form['entity_id']['#type'] = 'hidden';
        $contact_form['entity_id']['#attributes']['disabled'] = TRUE;

        // Hide the IEF entity_id select list field on the Address.
        $addr_form['entity_id']['#type'] = 'hidden';
        $addr_form['entity_id']['#attributes']['disabled'] = TRUE;
      }

      // Make the Contact's first and last name required.
      $contact_form['firstName']['#required'] = true;
      $contact_form['lastName']['#required'] = true;

      // We want our validate function to be first so it adds the user's email to the contact before IEF does it's thing.
      array_unshift($contact_form['#element_validate'], 'xdruple_commerce_user_reg_form_validate');

      // Hide the primaryEmail field since we get this from the Drupal User's mail field.
      $contact_form['primaryEmail']['#type'] = 'hidden';
      $contact_form['primaryEmail']['#attributes']['disabled'] = TRUE;
    }
  }

  // Wrap any 'access checkout' items in 'access xtuple checkout' so we can
  // dynamically grant it.
  // @See: commerce_checkout_form_alter()
  if (strpos($form_id, 'views_form_commerce_cart_form_') === 0 ||
      strpos($form_id, 'views_form_ft_commerce_cart_form_') === 0) {

    // Only add the Checkout button if the cart form View shows line items.
    $view = reset($form_state['build_info']['args']);

    if (!empty($view->result)) {
      $form['actions']['checkout']['#access'] = xdruple_access(
        'views_form_commerce_cart_form',
        'view',
        'access checkout'
      );
    }
  }
}

/**
 * Validation function to modify the user reg form submit and copy the Drupal
 * user's email/username to xTuple contact's email field which is hidden from
 * the user.
 */
function xdruple_commerce_user_reg_form_validate(&$element_form, &$form_state, $complete_form) {
  global $rescued_clients;

  // Figure out if create_xtuple_user_association flag is set.
  $create_association = false;
  if (isset($form_state['values']['create_xtuple_user_association'])) {
    $create_association = $form_state['values']['create_xtuple_user_association'];
  }

  if (isset($complete_form['xd_contact_association'][LANGUAGE_NONE]['form']['erp_xdusercontactcontact'][LANGUAGE_NONE]['form'])) {
    // Clear out the 'xd_contact_association' part of the form so it's not used.
    if (empty($create_association)) {
      $contact_form = &$complete_form['xd_contact_association'][LANGUAGE_NONE]['form']['erp_xdusercontactcontact'][LANGUAGE_NONE]['form'];
      $addr_form = &$contact_form['erp_xdcontactaddress'][LANGUAGE_NONE]['form'];

      // Make the Contact's first and last name not required because we're removed it from the form.
      $contact_form['firstName']['#required'] = false;
      $contact_form['lastName']['#required'] = false;

      // Make the Address fields not required because we're removed it from the form.
      // Recurse through all children.
      foreach (element_children($addr_form) as $key) {
        if (isset($addr_form[$key]) && $addr_form[$key]) {
          $addr_form[$key]['#required'] = false;
        }
      }

      if ($form_state['triggering_element']['#type'] === 'submit') {
        unset($form_state['complete form']['xd_contact_association']);
        unset($form_state['input']['xd_contact_association']);
        unset($form_state['values']['xd_contact_association']);
      }
    }
  }

  // If this is create customer, check the email agianst customer names.
  if (isset($element_form['#id']) && strpos($element_form['#id'], 'edit-xd-contact-association-und-form-create-new-customer') !== false) {
    if (!empty($create_association)) {
      // On main form submit.
      if ($form_state['triggering_element']['#type'] === 'submit') {
        $create_customer_parents = $element_form['#parents'];
        $create_customer = drupal_array_get_nested_value($form_state['values'], $create_customer_parents);

        if (isset($complete_form['xd_contact_association'][LANGUAGE_NONE]['form']['#entity'])) {
          $association_entity = $complete_form['xd_contact_association'][LANGUAGE_NONE]['form']['#entity'];
        } else {
          $association_entity = null;
        }

        if (!empty($create_customer) && isset($association_entity->is_new) &&
          $association_entity->is_new) {

          // If this is a new create customer that wasn't checked before on a new entity.
          $check_existing_customer = true;
        } elseif (!empty($create_customer) &&
          isset($association_entity->originalEntity['create_new_customer']) &&
          $create_customer != $association_entity->originalEntity['create_new_customer']) {

          // If this is an old entity and it wasn't checked before.
          $check_existing_customer = true;
        } else {
          $check_existing_customer = false;
        }

        if ($check_existing_customer) {
          // Search xTuple for existing customer with email as their name.
          $conditions = array(
            'query' => array(
              'number' => array(
                'EQUALS' => strtoupper($form_state['values']['mail']),
              ),
            ),
          );
          $existing_customers = entity_load('xtuple_xdcustomerrelation', FALSE, $conditions);

          if (count($existing_customers) > 0) {
            // Set form error.
            $message = 'The Email address: %email is already in use. Cannot create a Customer with this email address. Please use a different Email address, !login_url or !reset_url.';
            $message = t($message, array(
                '%email' => $form_state['values']['mail'],
                '!login_url' => l(t('Log In'), "user"),
                '!reset_url' => l(t('Request a new password'), "user/password"),
              )
            );
            form_set_error('mail', $message);
          }
        }
      }
    }
  }

  if (isset($element_form['#id']) && $element_form['#id'] === 'edit-xd-contact-association-und-form-xdruple-site') {
    if (!empty($create_association)) {
      $site_parents = $element_form['#parents'];
      $site_name = $rescued_clients['xtuple']['settings']['discovery']['application_name'];

      // Set the site to the default before we save.
      drupal_array_set_nested_value($form_state['values'], $site_parents, $site_name);
    }
  }

  if (isset($element_form['#entity_type'], $element_form['#parents']) && $element_form['#entity_type'] = 'xtuple_xdcontact') {
    if (!empty($create_association) && isset($form_state['values']['mail'])) {
      $cntct_email_parents = $element_form['#parents'];
      $cntct_email_parents[] = 'primaryEmail';

      $email_set = drupal_array_get_nested_value($form_state['values'], $cntct_email_parents);

      // On main form submit.
      if ($form_state['triggering_element']['#type'] === 'submit') {
        // When this is a new contact, not "Use existing Contact".
        if (isset($element_form['#entity']->is_new) && $element_form['#entity']->is_new) {
          // Check the Drupal email address against contacts.
          $conditions = array(
            'query' => array(
              'primaryEmail' => array(
                'EQUALS' => $form_state['values']['mail'],
              ),
            ),
          );
          $existing_contacts = entity_load('xtuple_xdcontact', FALSE, $conditions);

          if (count($existing_contacts) > 0) {
            // Set form error.
            $message = 'The Email address: %email is already in use. Please use a different Email address, !login_url or !reset_url.';
            $message = t($message, array(
                '%email' => $form_state['values']['mail'],
                '!login_url' => l(t('Log In'), "user"),
                '!reset_url' => l(t('Request a new password'), "user/password"),
              )
            );
            form_set_error('mail', $message);
          }
        }
      }

      // Only set the email if this contact doesn't have one.
      if (empty($email_set)) {
        // Set the contact's primaryEmail to the Drupal user's email/username before we save.
        drupal_array_set_nested_value($form_state['values'], $cntct_email_parents, $form_state['values']['mail']);
      }

      // Unset the IEF entity so it gets reprocessed if there's a validation error.
      $form_state['inline_entity_form'][$element_form['#ief_id']]['entities'] = array();
    }
  }
}

/**
 * Implements hook_theme().
 */
function xdruple_commerce_theme() {
  $items = array(
    'xdruple_commerce_sub_title' => array(
      'variables' => array('subTitle' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-sub-title',
    ),
    'xdruple_commerce_product_weight' => array(
      'variables' => array('productWeight' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-product-weight',
    ),
    'xdruple_commerce_length' => array(
      'variables' => array('prodLength' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-length',
    ),
    'xdruple_commerce_width' => array(
      'variables' => array('prodWidth' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-width',
    ),
    'xdruple_commerce_height' => array(
      'variables' => array('prodHeight' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-height',
    ),
    'xdruple_commerce_package_weight' => array(
      'variables' => array('packageWeight' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-package-weight',
    ),
    'xdruple_commerce_pack_length' => array(
      'variables' => array('packLength' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-pack-length',
    ),
    'xdruple_commerce_pack_width' => array(
      'variables' => array('packWidth' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-pack-width',
    ),
    'xdruple_commerce_pack_height' => array(
      'variables' => array('packHeight' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-pack-height',
    ),
    'xdruple_commerce_class_code' => array(
      'variables' => array('classCode' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-class-code',
    ),
    'xdruple_commerce_product_category' => array(
      'variables' => array('productCategory' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-product-category',
    ),
    'xdruple_commerce_inventory_unit' => array(
      'variables' => array('inventoryUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-inventory-unit',
    ),
    'xdruple_commerce_price_unit' => array(
      'variables' => array('priceUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-price-unit',
    ),
    'xdruple_commerce_uom_ratio' => array(
      'variables' => array('uomRatio' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-uom-ratio',
    ),
    'xdruple_commerce_dimension_unit' => array(
      'variables' => array('dimensionUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-dimension-unit',
    ),
    'xdruple_commerce_weight_unit' => array(
      'variables' => array('weightUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-weight-unit',
    ),
    'xdruple_commerce_physical_prod_unit' => array(
      'variables' => array('physicalProdUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-physical-prod-unit',
    ),
    'xdruple_commerce_physical_pack_unit' => array(
      'variables' => array('physicalPackUnit' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-physical-pack-unit',
    ),
    'xdruple_commerce_notes' => array(
      'variables' => array('notes' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-notes',
    ),
    'xdruple_commerce_ex_descrip' => array(
      'variables' => array('extDescrip' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'template' => 'xdruple-commerce-ext-descrip',
    ),
    'xdruple_commerce_cart_dropdown' => array(
      'variables' => array(
        'link' => NULL,
        'title' => NULL,
        'count' => NULL,
        'amount' => NULL,
      ),
      'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
      'file' => 'theme.inc',
      'template' => 'xdruple-commerce-cart-dropdown',
    ),
  );

  $items['xdruple_commerce_similar_product_link_default'] = array(
    'variables' => array(
      'product_id' => 0,
      'style' => '',
    ),
    'path' => drupal_get_path('module', 'xdruple_commerce') . '/theme',
    'file' => 'theme.inc',
    'template' => 'xdruple-commerce-similar-product-link-default',
  );

  $items += \CDD\OpenCDD\Theme\Block::themeDefinition('cart_dropdown', array(
    'hide_empty_title'   => TRUE,
    'hide_empty_content' => TRUE,
    'hide_empty_block'   => TRUE,
  ));


  return $items;
}

/**
 * Implements hook_email_registration_name().
 */
// function xdruple_commerce_email_registration_name($edit, $account) {
//   $name = $account->mail;

//   return email_registration_cleanup_username($name);
// }

/**
 * Implements hook_user_insert().
 */
function xdruple_commerce_user_insert(&$edit, $account, $category) {
  $field_name = 'xd_contact_association';

  // Get the XdUserContact uuid from this user's Entity Reference and load that entity.
  if (isset($edit[$field_name][LANGUAGE_NONE][0]['target_id'])) {
    $field = field_info_field($field_name);
    $entity_type = $field['settings']['target_type'];

    $user_contact_key = $edit['xd_contact_association'][LANGUAGE_NONE][0]['target_id'];

    // Update the uid now that one exists.
    $user_contact = entity_load_single($entity_type, $user_contact_key);
    $user_contact->drupalUserUuid = $account->uuid;

    // Save it back to xTuple.
    entity_save($entity_type, $user_contact);
  }
}

/**
 * Implements hook_user_update().
 */
function xdruple_commerce_user_update(&$edit, $account, $category) {
  $field_name = 'xd_contact_association';

  // Get the XdUserContact uuid from this user's Entity Reference and load that entity.
  if (isset($edit[$field_name][LANGUAGE_NONE][0]['target_id'])) {
    $field = field_info_field($field_name);
    $entity_type = $field['settings']['target_type'];

    $user_contact_key = $edit['xd_contact_association'][LANGUAGE_NONE][0]['target_id'];

    // Update the uid now that one exists.
    $user_contact = entity_load_single($entity_type, $user_contact_key);
    $user_contact->drupalUserUuid = $account->uuid;

    // Save it back to xTuple.
    entity_save($entity_type, $user_contact);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Product UI module instantiates the Product add/edit form alter the
 * form here to xTuple properties as fields.
 *
 * @see commerce_product_ui_product_form()
 */
function xdruple_commerce_form_commerce_product_ui_product_form_alter(&$form, &$form_state) {
  $product = $form_state['commerce_product'];
  $op = 'edit';
  $entityType = 'commerce_product';
  $entityInfo = entity_get_info($entityType);
  $handler_class = $entityInfo['operations ui']['operations'][$op]['handler'];

  // Break the reference to $form_state.
  $foo_state = (array) clone ((object) $form_state);

  $excluded_fields = array(
    'product_id',
    'revision_id',
    'sku',
    'title',
    'type',
    'language',
    'uid',
    'status',
    'created',
    'changed',
    'data',
    'commerce_price',
    'urls', // URLs are loaded through the 'erp_xdproducturls' field.
    'characteristics', // Characteristics are loaded through the 'erp_xdproductcharacteristics' field.
  );

  // Get the xtuple form version from our controler and loop over our fields in that
  // form and add to the commerce_product from.
  $xdruple_form = entity_operations_operation_form(array(), $foo_state, 'XdProduct', $handler_class, $op, $product);
  foreach ($entityInfo['json-schema']['XdProduct']['properties'] as $prop_name => $prop_value) {
    // Skip the fields that are already handled or should not be shown.
    if (!in_array($prop_name, $excluded_fields)) {
      $form[$prop_name] = $xdruple_form[$prop_name];
      if (in_array($prop_name, array('notes', 'extDescrip'))) {
        $form[$prop_name]['#type'] = 'textarea';
        $form[$prop_name]['#rows'] = 4;
      }
      $form[$prop_name]['#weight'] = -3;
    }
  }
}

/**
 * Implements hook_field_attach_submit.
 */
function xdruple_commerce_field_attach_submit($entity_type, $entity, $form, $form_state) {
  if ($entity_type === 'commerce_product') {
    // Save xTuple parameters back into the product entity object.
    $entity->subTitle = $form_state['values']['subTitle'];
    $entity->notes = $form_state['values']['notes'];
    $entity->extDescrip = $form_state['values']['extDescrip'];
    $entity->productWeight = $form_state['values']['productWeight'];
    $entity->prodLength = $form_state['values']['prodLength'];
    $entity->prodWidth = $form_state['values']['prodWidth'];
    $entity->prodHeight = $form_state['values']['prodHeight'];
    $entity->packageWeight = $form_state['values']['packageWeight'];
    $entity->packLength = $form_state['values']['packLength'];
    $entity->packWidth = $form_state['values']['packWidth'];
    $entity->packHeight = $form_state['values']['packHeight'];
    $entity->classCode = $form_state['values']['classCode'];
    $entity->productCategory = $form_state['values']['productCategory'];
    $entity->priceUnit = $form_state['values']['priceUnit'];
    $entity->uomRatio = $form_state['values']['uomRatio'];
    $entity->inventoryUnit = $form_state['values']['inventoryUnit'];
    $entity->weightUnit = $form_state['values']['weightUnit'];
    $entity->dimensionUnit = $form_state['values']['dimensionUnit'];
    $entity->physicalProdUnit = $form_state['values']['physicalProdUnit'];
    $entity->physicalPackUnit = $form_state['values']['physicalPackUnit'];
  }
}

/**
 * Implements hook_entity_query_alter.
 *
 * EntityFieldQuery used in _commerce_product_match_products_standard() does not
 * allow OR clauses. Alter the query to string match on sku OR title.
 *
 * @param $query
 */
function xdruple_commerce_entity_query_alter(&$query) {
  if (isset($query->tags['commerce_sku_or_title_match'])) {
    $string = $query->metaData['commerce_sku_or_title_match']->string;
    $match = $query->metaData['commerce_sku_or_title_match']->match;

    if (isset($string, $match)) {
      // Build a where clause matching on either the SKU or title.

      // TODO: xTuple doesn't currently support an operator.
      switch ($match) {
        case 'contains':
          $query->propertyCondition('q', $string, 'CONTAINS');
          break;

        case 'starts_with':
          $query->propertyCondition('q', $string, 'CONTAINS');
          break;

        case 'equals':
        default:
          $query->propertyCondition('q', $string, '=');
          break;
      }
    }
  }
}

/**
 * XM.XdProduct.XdProductFetch POST query.
 *
 * Query the dispatch function XM.XdProduct.XdProductFetch to
 * get a filtered list of items that a Customer is allowed to see.
 *
 * @param string $discovery_client The API client name. e.g. 'xtuple'
 * @param string $resource The API resource name. e.g. 'ItemSiteListItem'
 * @param array $optParams The structured query to perform.
 *
 * @return array The query result response.
 */
function xdruple_commerce_api_customer_exclusive_item_list($discovery_client = 'xtuple', $resource = 'XdProduct', $optParams = array(), $data_only = true) {
  // When exclusive_items setting is off, just query rescued_api_resource_list().
  if (!variable_get('xdruple_commerce_filter_exclusive_items', FALSE)) {
    $result = rescued_api_resource_list($discovery_client, $resource, $optParams, false);
  } else {
    $service = wsclient_service_load($discovery_client);
    $endpoint = $service->endpoint();
    $client = $endpoint->client();

    $customer = xdruple_rescued_session_get('customer');
    $shipto = xdruple_rescued_session_get('ship_to');
    $scheduled_date = xdruple_rescued_scheduled_date();

    if (!empty($customer)) {
      $optParams['query']['customer'] = array(
        'EQUALS' => $customer,
      );
    }
    if (!empty($shipto)) {
      $optParams['query']['shipto'] = array(
        'EQUALS' => $shipto,
      );
    }
    if (!empty($scheduled_date)) {
      $optParams['query']['effectiveDate'] = array(
        'EQUALS' => $scheduled_date,
      );
    }

    $postBody = array(
      'attributes' => array(
        rescued_format_post_query_options($optParams),
      ),
    );

    $params = array('postBody' => $postBody);

    // POST the service request.
    $result = $client->$resource->xdProductFetch($params);
  }

  if ($data_only) {
    return isset($result['data']) ? $result['data'] : array();
  } else {
    return isset($result) ? $result : array();
  }
}

/**
 * XM.Customer.itemPrice POST query.
 *
 * Query the dispatch function XM.Customer.itemPrice to get a item price quote.
 *
 * @param string $discovery_client The API client name. e.g. 'xtuple'
 * @param string $resource The API resource name. e.g. 'Customer'
 * @param array $postBody The structured query to perform.
 * @param array $optParams Additional option parameters.
 *
 * @return array The query result response.
 */
function xdruple_commerce_api_customer_item_price($discovery_client = 'xtuple', $resource = 'Customer', $postBody, $optParams = array()) {
  $service = wsclient_service_load($discovery_client);
  $endpoint = $service->endpoint();
  $client = $endpoint->client();

  $params = array('postBody' => $postBody);
  $params = array_merge($params, $optParams);

  // POST the service request.
  $result = $client->$resource->itemPrice($params);

  return $result['price'];
}

function xdruple_commerce_get_customer_line_item_price($line_item) {
  /** @var stdClass $user */
  global $user;

  /** @var Xtuple\Xdruple\Session\RescuedSession $session */
  $session = extensions_get_session();
  if ((!$session->getRescued('customer') || !$session->getRescued('ship_to') || !$session->getRescued('site'))
    && $user->uid !== 0
  ) {
    // We cannot get a price quote without all of these set.
    return;
  }

  if ($user->uid === 0 && !variable_get('xdruple_checkout_use_guest_customer_price_schedule', FALSE)) {
    // Do not get price quote from guest customer price schedule.
    return;
  }

  if ($user->uid === 0) {
    // Get anonymous checkout defaults from control panel.
    $customer = variable_get('xdruple_checkout_guest_customer', null);
    $shipto   = null;
    $site     = variable_get('xdruple_commerce_default_warehouse', null);
  } else {
    $customer = $session->getRescued('customer');
    $shipto   = $session->getRescued('ship_to');
    $site     = $session->getRescued('site');
  }

  $date = xdruple_rescued_scheduled_date('tomorrow');

  $cid = 'xdruple_commerce_customer_line_item_price-' .
         $customer . '-' .
         $line_item->line_item_label . '-' .
         strval($line_item->quantity) . '-' .
         strval($date) . '-' .
         $shipto . '-' .
         $site;
  $cache = cache_get($cid, 'cache');

  if (empty($cache)) {
    $options = array(
      'asOf'      => $date, // The scheduled date for the order.
      'siteId'    => $site,
      'effective' => format_date(REQUEST_TIME, 'custom', 'Y-m-d'), // Always today.
    );

    if (!empty($shipto)) {
      $options['shiptoId'] = $shipto;
    }

    $postBody = array(
      'attributes' => array(
        $customer,
        $line_item->line_item_label,
        $line_item->quantity,
        $options,
      ),
    );

    // Make the itemPrice service request.
    $price = xdruple_commerce_api_customer_item_price('xtuple', 'Customer', $postBody);

    cache_set($cid, $price, 'cache', CACHE_TEMPORARY);
  } else {
    $price = $cache->data;
  }

  if (isset($price) && $price >= 0) {
    $price = round($price * 100); // Drupal Commerce doesn't use decimals for prices.
    $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['amount'] = $price;
    $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['data']['components']['0']['price']['amount'] = $price;
  }
}

/**
 * Implements hook_commerce_product_calculate_sell_price_line_item_alter().
 *
 * @param $line_item
 *   The product line item used for sell price calculation.
 */
function xdruple_commerce_commerce_product_calculate_sell_price_line_item_alter($line_item) {
  // Alter the list price.
  if ($line_item->type === 'product') {
    xdruple_commerce_get_customer_line_item_price($line_item);
  }
}


/**
 * Implements hook_commerce_cart_line_item_refresh().
 *
 * @param $line_item
 *   The product line item used for sell price calculation.
 *
 * @param $order_wrapper
 *   The order.
 */
function xdruple_commerce_commerce_cart_line_item_refresh($line_item, $order_wrapper){
  // Alter the list price.
  if ($line_item->type === 'product') {
    xdruple_commerce_get_customer_line_item_price($line_item);
  }
}

/**
 * Helper function to format the Currency for this field.
 *
 * @param float $amount
 *   The amount to format.
 * @param object $currency
 *   The Currency object.
 *
 * @return Formatted amount.
 */
function _xdruple_commerce_currency_format($amount, $currency) {
  // Add commas and round to two places.
  $amount = number_format(round($amount, 2), 2);

  $format = $currency->symbol . $amount;

  return $format;
}

/**
 * Helper function to format a link to the product page.
 *
 * @param string $product
 *
 * @return Formatted link to the product page.
 */
function _xdruple_commerce_product_format($item) {
  $query = new EntityFieldQuery();
  $product = $query->entityCondition('entity_type', 'commerce_product')
                ->propertyCondition('sku', $item['number'], '=')
                ->execute();

  if (count($product['commerce_product']) > 0) {
    $product_id = key($product['commerce_product']);
    // Create link to product page.
    $format = l($product['commerce_product'][$product_id]->sku, 'products/' . $product_id);
  } else {
    $format = $item['number'];
  }

  return $format;
}

function xdruple_commerce_xtuple_xdshipto_view_alter(&$build, $entity_type) {
  $build['#page'] = TRUE;

  if (!empty($build['isDefault']['#access'])) {
    $build['isDefault']['#access'] = FALSE;
  }
  if (!empty($build['number']['#access'])) {
    $build['number']['#access'] = FALSE;
  }
  if (!empty($build['name'][0]['#markup'])) {
    if (!empty($build['customer']['#access'])) {
      $build['customer']['#access'] = FALSE;
    }
    $build['name']['#label_display'] = 'hidden';
  }
  else {
    $build['name']['#access']            = FALSE;
    $build['customer']['#label_display'] = 'hidden';
  }
}

function xdruple_commerce_xtuple_xdcustomerrelation_view_alter(&$build, $entity_type) {
  $build['#page'] = TRUE;
  if (empty($build['erp_xdcustomerrelationbillingcontact'][0]['#markup'])) {
    $build['erp_xdcustomerrelationbillingcontact']['#access'] = FALSE;
  }
  if (empty($build['erp_xdcustomerrelationshipto'][0]['#markup'])) {
    $build['erp_xdcustomerrelationshipto']['#access'] = FALSE;
  }
  if (empty($build['erp_xdcustomerrelationcorrespondencecontact'][0]['#markup'])) {
    $build['erp_xdcustomerrelationcorrespondencecontact']['#access'] = FALSE;
  }
  if (!empty($build['isActive']['#access'])) {
    $build['isActive']['#access'] = FALSE;
  }
  if (!empty($build['number']['#access'])) {
    $build['number']['#access'] = FALSE;
  }
  if (!empty($build['name'][0]['#markup'])) {
    $build['name']['#label_display'] = 'hidden';
  }
  else {
    $build['name']['#access'] = FALSE;
  }
}

function xdruple_commerce_xtuple_xdcontact_view_alter(&$build, $entity_type) {
  $build['#page'] = TRUE;
  $name           = array();
  if (!empty($build['firstName'][0]['#markup'])) {
    $name[] = $build['firstName'][0]['#markup'];
  }
  if (!empty($build['lastName'][0]['#markup'])) {
    $name[] = $build['lastName'][0]['#markup'];
  }
  $build['firstName']['#label_display'] = 'hidden';
  $build['lastName']['#access']         = FALSE;
  $build['firstName'][0]['#markup']     = implode(' ', $name);
  if (empty($build['firstName'][0]['#markup'])) {
    $build['firstName']['#access'] = FALSE;
  }

  $build['phone']['#label_display']        = 'hidden';
  $build['primaryEmail']['#label_display'] = 'hidden';

  $active_menu_item = menu_get_item();
  if ($active_menu_item['path'] == 'checkout/%/%'
    && !empty($active_menu_item['page_arguments'][1]['page_id'])
    && $active_menu_item['page_arguments'][1]['page_id'] == 'review'
  ) {
    $build['erp_xdcontactaddress']['#access'] = FALSE;
  }
  else {
    $build['erp_xdcontactaddress']['#label_display'] = 'above';
  }
}

function xdruple_commerce_xtuple_xdaddress_view_alter(&$build, $entity_type) {
  $build['#page'] = TRUE;
  if (!empty($build['line1'][0]['#markup'])) {
    $build['line1']['#label_display'] = 'hidden';
  }
  else {
    $build['line1']['#access'] = FALSE;
  }
  if (!empty($build['line2'][0]['#markup'])) {
    $build['line2']['#label_display'] = 'hidden';
  }
  else {
    $build['line2']['#access'] = FALSE;
  }
  if (!empty($build['line3'][0]['#markup'])) {
    $build['line3']['#label_display'] = 'hidden';
  }
  else {
    $build['line3']['#access'] = FALSE;
  }

  $city_state_zip = array();
  if (!empty($build['city'][0]['#markup'])) {
    $city_state_zip[] = $build['city'][0]['#markup'];
  }
  if (!empty($build['state'][0]['#markup'])) {
    $city_state_zip[] = $build['state'][0]['#markup'];
  }
  if (!empty($build['postalCode'][0]['#markup'])) {
    $city_state_zip[] = $build['postalCode'][0]['#markup'];
  }
  $build['city'][0]['#markup']     = implode(', ', $city_state_zip);
  $build['city']['#label_display'] = 'hidden';
  $build['state']['#access']       = FALSE;
  $build['postalCode']['#access']  = FALSE;

  $build['country']['#label_display'] = 'hidden';
  if (empty($build['country'][0]['#markup'])) {
    $build['country']['#access'] = FALSE;
  }

  if (!empty($build['number'])) {
    $build['number']['#access'] = FALSE;
  }
}

function xdruple_commerce_xtuple_xdusercontact_view_alter(&$build, $entity_type) {
  $build['#page'] = TRUE;

  $build['uuid']['#access'] = FALSE;
  $build['xdruple_site']['#access'] = FALSE;
  $build['drupalUserUuid']['#access'] = FALSE;
  $build['create_new_customer']['#access'] = FALSE;
  $build['contact']['#access'] = FALSE;
}

/**
 * Implements hook_theme_registry_alter()
 */
function xdruple_commerce_theme_registry_alter(&$theme_registry) {
  $module = drupal_get_path('module', 'xdruple_commerce');
  $theme_registry['commerce_checkout_review']['file'] = 'xdruple_commerce.module';
  $theme_registry['commerce_checkout_review']['theme path'] = $module;
  $theme_registry['commerce_checkout_review']['includes'][0] = "$module/xdruple_commerce.module";
  $theme_registry['commerce_checkout_review']['function'] = 'xdruple_commerce_checkout_review';
}

/**
 * Implements hook_user_view_alter()
 */
function xdruple_commerce_user_view_alter(&$build) {
  $build['summary']['#access'] = FALSE;
}

function xdruple_commerce_checkout_review($variables) {
  $rows = array();

  foreach ($variables['form']['#data'] as $pane_id => $pane) {
    $fieldset = theme('fieldset', array(
      'element' => array(
        '#title' => $pane['title'],
        '#value' => $pane['data'],
        '#children' => '',
        '#attributes' => array(
          'class' => array(
            'checkout-review-fieldset',
            'checkout-review-fieldset--' . drupal_clean_css_identifier($pane_id)
          ),
        ),
      ),
    ));

    $rows[] = theme('html_tag', array(
      'element' => array(
        '#tag' => 'div',
        '#value' => $fieldset,
        '#attributes' => array(
          'class' => array(
            'checkout-review-pane',
            'checkout-review-pane--' . drupal_clean_css_identifier($pane_id),
          ),
        ),
      )
    ));
  }

  return implode('', $rows);
}

function xdruple_commerce_field_display_alter(&$display, $context) {
  if ($context['entity_type'] == 'xtuple_xdshipto') {
    if ($context['field']['field_name'] == 'xd_ship_to') {
      $display['label'] = 'hidden';
    }
    if ($display['module'] == 'entityreference') {
      $display['type'] = 'entityreference_entity_view';
      $display['settings']['view_mode'] = 'default';
      $display['settings']['links'] = TRUE;
    }
    if ($context['field']['field_name'] == 'erp_xdshiptocontact') {
      $display['weight'] = 19;
    }
  }
}

function xdruple_commerce_entity_view_alter(&$build, $type) {
  if ($type == 'commerce_customer_profile') {
    if ($build['#bundle'] == 'shipping') {
      if (!empty($build['xd_ship_to']['#items'][0]['target_id'])) {
        $target_id = $build['xd_ship_to']['#items'][0]['target_id'];
        $ship_to = &$build['xd_ship_to'][0]['xtuple_xdshipto'][$target_id];
        if (!empty($ship_to['erp_xdshiptoaddress'])) {
          $field = $ship_to['erp_xdshiptoaddress'];
          $field['#field_name'] = 'xd_ship_to_address';
          $field['#field_type'] = 'entityreference';
          $field['#title'] = t('Ship To Address');
          $build['xd_ship_to_address'] = $field;
          $ship_to['erp_xdshiptoaddress']['#access'] = FALSE;
        }
        if (!empty($ship_to['erp_xdshiptocontact'])) {
          $field = $ship_to['erp_xdshiptocontact'];
          $field['#field_name'] = 'xd_ship_to_contact';
          $field['#field_type'] = 'entityreference';
          $field['#title'] = t('Ship To Contact');
          $build['xd_ship_to_contact'] = $field;
          $ship_to['erp_xdshiptocontact']['#access'] = FALSE;
        }
      }
      else {
        $name = '';
        if (!empty($build['xd_ship_to_contact']['#items'][0]['target_id'])) {
          $tid = $build['xd_ship_to_contact']['#items'][0]['target_id'];
          $name = $build['xd_ship_to_contact'][0]['xtuple_xdcontact'][$tid]['firstName'][0]['#markup'];
        }

        $markup = '';
        $markup .= '<div class="field field-name-xd-ship-to field-type-entityreference field-label-above">';
        if ($name) {
          $markup .= '<div class="field-label">'. t('Ship to') .':&nbsp;</div>';
          $markup .= '<div class="field-items"><div class="field-item even">'. $name . '</div></div>';
        }
        $markup .= '</div>';
        $build['xd_ship_to'] = array(
          '#markup' => $markup,
          '#weight' => -30,
        );
      }
    }
  }

  if ($type == 'commerce_product' && $build['#view_mode'] == 'full') {
    _xdruple_commerce_product_entity_view_alter($build);
  }
}

/**
 * Implements hook_commerce_checkout_pane_info()
 */
function xdruple_commerce_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['purchased_items'] = array(
    'title' => t('Purchased items'),
    'base' => 'xdruple_commerce_checkout_purchased_items_pane',
    'page' => 'complete',
    'fieldset' => TRUE,
    'locked' => FALSE,
    'weight' => 1,
  );

  return $checkout_panes;
}

/**
 * Implements hook_commerce_checkout_pane_info_alter()
 */
function xdruple_commerce_commerce_checkout_pane_info_alter(&$checkout_panes) {
  $checkout_panes['checkout_completion_message']['base'] = 'xdruple_commerce_checkout_completion_message_pane';
}

/**
 * Callback for checkout_completion_message pane settings form
 *
 * /admin/commerce/config/checkout/form/pane/checkout_completion_message
 */
function xdruple_commerce_checkout_completion_message_pane_settings_form($checkout_pane) {
  $form = array();

  $message = variable_get('commerce_checkout_completion_message', xdruple_commerce_checkout_completion_message_default());

  $form['container'] = array(
    '#type'   => 'container',
    '#access' => filter_access(filter_format_load($message['format'])),
  );

  $form['container']['commerce_checkout_completion_message'] = array(
    '#type'          => 'text_format',
    '#title'         => t('Checkout completion message'),
    '#default_value' => $message['value'],
    '#format'        => $message['format'],
  );

  $var_info = array(
    'site'           => array(
      'type'        => 'site',
      'label'       => t('Site information'),
      'description' => t('Site-wide settings and other global information.'),
    ),
    'commerce_order' => array(
      'label' => t('Order'),
      'type'  => 'commerce_order',
    ),
    'user'           => array(
      'label' => t('User'),
      'type'  => 'user',
    ),
  );

  $form['container']['commerce_checkout_completion_message_help'] = RulesTokenEvaluator::help($var_info);

  return $form;
}

/**
 * Callback for checkout_completion_message pane (checkout/%/complete page)
 */
function xdruple_commerce_checkout_completion_message_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $pane_form = array();
  global $user;

  $message = variable_get('commerce_checkout_completion_message', xdruple_commerce_checkout_completion_message_default());

  $message['value'] = commerce_i18n_string('commerce:checkout:complete:message', $message['value'], array(
    'sanitize' => FALSE,
  ));

  // TODO: Add anonymous email template.
  if ($user->uid === 0) {
    $user->mail = $order->mail;
  }

  $message['value'] = token_replace($message['value'], array(
    'commerce-order' => $order,
    'user'           => $user,
  ), array(
    'clear' => TRUE,
  ));

  if ($user->uid === 0) {
    unset($user->mail);
  }

  $message['value'] = check_markup($message['value'], $message['format']);

  $pane_form['message'] = array(
    '#markup' => '<div class="checkout-completion-message">' . $message['value'] . '</div>',
  );

  return $pane_form;
}

/**
 * Helper function, returns default checkout completion message
 */
function xdruple_commerce_checkout_completion_message_default() {
  $value  = '';
  $format = 'htmlpurifier_basic';
  if (filter_format_load($format)) {
    $value .= '<p>Your order number is <a href="[commerce-order:view-url]">[commerce-order:order-number]</a>.</p>';
    $value .= '<p>You can <a href="[commerce-order:url]">view your order</a> on your <a href="user/[user:uid]/pending-orders">pending orders page</a> when logged in.</p>';
    $value .= '<p>We sent an order confirmation e-mail to you at <strong>[user:mail]</strong>.</p>';
    $value .= '<p><a href="[site:url]">Return to the front page.</a></p>';
  }
  else {
    $value .= 'Your order number is [commerce-order:order-number]. You can view your order on your account page when logged in.';
    $format = filter_fallback_format();
  }

  return array(
    'value'  => $value,
    'format' => $format,
  );
}

/**
 * Callback for purchased_items pane (checkout/%/complete page)
 */
function xdruple_commerce_checkout_purchased_items_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $pane_form = array();

  module_load_include('inc', 'commerce_cart', 'includes/commerce_cart.checkout_pane');
  $pane_form['cart_contents'] = array(
    '#markup' => commerce_cart_contents_pane_review($form, $form_state, $checkout_pane, $order),
  );

  return $pane_form;
}

/**
 * Implements hook_form_FORM_ID_alter for entity_operations_operation_form_xtuple_xdshipto
 */
function xdruple_commerce_form_entity_operations_operation_form_xtuple_xdshipto_edit_alter(&$form, $form_state) {
  $form['actions']['#weight'] = 100;
}

function xdruple_commerce_form_entity_operations_operation_form_alter(&$form, $form_state) {
  $form['actions']['#weight'] = 100;
}


function _xdruple_commerce_get_cart_summary() {
  $summary = array();

  global $user;

  $order = commerce_cart_order_load($user->uid);
  if ($order) {
    $wrapper = entity_metadata_wrapper('commerce_order', $order);
    $count   = commerce_line_items_quantity($wrapper->commerce_line_items, commerce_product_line_item_types());

    $summary = array(
      'count'    => $count,
      'total'    => $order->commerce_order_total['und'][0]['amount'],
      'currency' => $order->commerce_order_total['und'][0]['currency_code'],
    );
  }

  return $summary;
}

function xdruple_commerce_cart_dropdown_block() {
  $output = '';

  $summary = _xdruple_commerce_get_cart_summary();
  if (!empty($summary['count']) && $summary['count'] > 0) {
    $output .= theme('xdruple_commerce_cart_dropdown', array(
      'title'  => t('My cart'),
      'count'  => format_plural($summary['count'], '1 item', '@count items'),
      'amount' => commerce_currency_format($summary['total'], $summary['currency']),
    ));
  }
  else {
    $output .= theme('xdruple_commerce_cart_dropdown', array(
      'title' => t('My cart is empty'),
    ));
  }

  return $output;
}

function xdruple_commerce_rules_condition_info_alter(&$conditions) {
  if (isset($conditions['commerce_order_compare_address'])) {
    $conditions['commerce_order_compare_address']['parameter']['address_field']['options list'] = 'xdruple_commerce_order_address_field_options_list';
    $conditions['commerce_order_compare_address']['parameter']['address_component']['options list'] = 'xdruple_commerce_order_address_component_options_list';
    $conditions['commerce_order_compare_address']['callbacks']['execute'] = 'xdruple_commerce_rules_compare_address';
  }
}

/**
 * Options list callback: address fields for the address comparison condition.
 */
function xdruple_commerce_order_address_field_options_list() {
  $options = array();

  // Retrieve a list of all xtuple address fields on customer profile bundles.
  $xtuple_entityreferences = commerce_info_fields('entityreference', 'commerce_customer_profile');
  $xtuple_field_names = array(
    'xd_ship_to_address' => '',
    'xd_ship_to' => '',
    'xd_bill_to_address' => '',
  );
  $xtuple_address_fields = array_intersect_key($xtuple_entityreferences, $xtuple_field_names);

  // Loop over every customer profile reference field on orders.
  foreach (commerce_info_fields('commerce_customer_profile_reference', 'commerce_order') as $field_name => $field) {
    // Retrieve the type of customer profile referenced by this field.
    $type = $field['settings']['profile_type'];

    // Loop over every address field looking for any attached to this bundle.
    foreach ($xtuple_address_fields as $address_field_name => $address_field) {
      if (in_array($type, $address_field['bundles']['commerce_customer_profile'])) {
        // Add it to the options list.
        $instance = field_info_instance('commerce_customer_profile', $address_field_name, $type);
        $translated_instance = commerce_i18n_object('field_instance', $instance);

        $options[commerce_customer_profile_type_get_name($type)][$field_name . '|' . $address_field_name] = check_plain($translated_instance['label']);
      }
    }
  }

  if (empty($options)) {
    drupal_set_message(t('No order addresses could be found for comparison.'), 'error');
  }

  return $options;
}

/**
 * Options list callback: components for the address comparison condition.
 */
function xdruple_commerce_order_address_component_options_list() {
  return array(
    'country'    => t('Country'),
    'line1'      => t('Thoroughfare (Street address)'),
    'line2'      => t('Premise (Building)'),
    'line3'      => t('Sub-premise (Suite)'),
    'city'       => t('Locality (City)'),
    'state'      => t('Administrative area (State / Province)'),
    'postalCode' => t('Postal code'),
  );
}

/**
 * Condition callback: compares an address component against the given value.
 */
function xdruple_commerce_rules_compare_address($order, $address_field, $component, $operator, $value) {
  list($field_name, $address_field_name) = explode('|', $address_field);

  // If we actually received a valid order...
  if (!empty($order)) {
    $wrapper = entity_metadata_wrapper('commerce_order', $order);

    // And if we can actually find the requested address data...
    if (!empty($wrapper->{$field_name}) && !empty($wrapper->{$field_name}->{$address_field_name})) {
      $address = $wrapper->{$field_name}->{$address_field_name}->value();

      if (empty($address)) {
        return FALSE;
      }

      // Get the address.
      if ($address_field_name === 'xd_ship_to') {
        $xtuple_address = json_decode(json_encode($address->address), FALSE);;
      } else {
        $xtuple_address = $address;
      }

      // Perform the comparison in upper case.
      $address_component = drupal_strtoupper($xtuple_address->{$component});
      $value = drupal_strtoupper($value);

      // Make a comparison based on the operator.
      switch ($operator) {
        case 'equals':
          return $address_component == $value;
        case 'begins with':
          return strpos($address_component, $value) === 0;
        case 'contains':
          return strpos($address_component, $value) !== FALSE;
        case 'is one of':
          $list = preg_split('/[\n\r]+/', $value);
          return array_search($address_component, $list) !== FALSE;
        case 'begins with one of':
          $list = preg_split('/[\n\r]+/', $value);
          foreach ($list as $item) {
            if (strpos($address_component, $item) === 0) {
              return TRUE;
            }
          }
          break;
      }
    }
  }

  return FALSE;
}

/**
 * Implements hook_module_implements_alter()
 */
function xdruple_commerce_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'modules_enabled') {
    $group = $implementations['xdruple_commerce'];
    unset($implementations['xdruple_commerce']);
    $implementations['xdruple_commerce'] = $group;
  }
}

/**
 * Implements hook_modules_enabled()
 *
 * - commerce_customer_modules_enabled() calls commerce_customer_configure_customer_fields() to ensure that all
 * modules that implement hook_commerce_customer_profile_type_info() were invoked and all profile type have
 * commerce_customer_address field. xDruple Commerce provides own fields to handle that and so this field should
 * always be removed
 *
 * @see commerce_customer_modules_enabled()
 * @see commerce_customer_configure_customer_fields()
 * @see commerce_customer_profile_type_info()
 */
function xdruple_commerce_modules_enabled($modules) {
  _xdruple_commerce_remove_commerce_customer_address();
}

/**
 * Helper functions. Removes all 'commerce_customer_address' fields.
 */
function _xdruple_commerce_remove_commerce_customer_address() {
  // Clear caches so xdruple_commerce module can override commerce module.
  drupal_flush_all_caches();
  drupal_static_reset();

  // Remove 'commerce_customer_address' fields on customer profiles. We use
  // xTuple integrated custom fields for this.
  $field_name = 'commerce_customer_address';
  foreach (commerce_customer_profile_types() as $profile_type) {
    $instance = field_info_instance('commerce_customer_profile', $field_name, $profile_type['type']);

    if (!empty($instance)) {
      // Delete the instance and field.
      // TODO: Do we really need to delete the field or just the instance?
      // This shouldn't be ran on an existing site that could have data in this
      // field, but that should never really happen. An existing site would
      // need to be migrated to an xTuple enabled site.
      field_delete_instance($instance, TRUE);
    }
  }

  field_purge_batch(10);
}

/**
 * Implements hook_views_default_views_alter()
 */
function xdruple_commerce_views_default_views_alter(&$views) {
  $commerce_orders = variable_get('commerce_orders_view_name', 'commerce_orders');
  if (isset($views[$commerce_orders])) {
    unset($views[$commerce_orders]->display['shopping_carts']);
    unset($views[$commerce_orders]->display['default']->display_options['filters']);
  }
}

/**
 * Builds configuration for Product entity full display.
 *
 * @return array
 */
function xdruple_commerce_get_product_display_config() {
  $config = array(
    'title' => array(
      'title' => 'Description',
      'label' => LABEL_INLINE,
    ),
    'classCode' => array(
      'title' => 'Manufacturer',
      'label' => LABEL_INLINE,
    ),
    'productCategory' => array(
      'title' => 'Category',
      'label' => LABEL_INLINE,
    ),
    'sku' => array(
      'title' => 'Part #',
      'label' => LABEL_INLINE,
    ),
    'priceUnit' => array(
      'title' => 'UOM',
      'label' => LABEL_INLINE,
    ),
    'prodWidth' => array(
      'title' => 'Width',
      'label' => LABEL_INLINE,
    ),
    'prodLength' => array(
      'title' => 'Length',
      'label' => LABEL_INLINE,
    ),
    'prodHeight' => array(
      'title' => 'Height',
      'label' => LABEL_INLINE,
    ),
    'dimensionUnit' => array(
      'title' => '',
      'label' => LABEL_INLINE,
    ),
    'barcode' => array(
      'title' => '',
      'label' => LABEL_INLINE,
    ),
    'xt_physical_weight' => array(
      'title' => 'Weight',
      'label' => LABEL_INLINE,
    ),
    'xt_physical_dimension' => array(
      'title' => 'Dimension',
      'label' => LABEL_INLINE,
    ),
    'extDescrip' => array(
      'title' => 'Extended description',
      'label' => LABEL_ABOVE,
    ),
    'xt_url_image_field' => array(
      'label' => LABEL_HIDDEN,
    ),
    'xt_url_file_field' => array(
      'title' => 'Product files',
      'label' => LABEL_ABOVE,
    ),
    'substitutes' => array(
      'title' => 'Related products',
      'label' => LABEL_ABOVE,
    ),
  );

  // Add default weight value
  $weight = 0;
  foreach ($config as &$item) {
    $item += array(
      'title' => '',
      'label' => LABEL_INLINE,
      'weight' => $weight,
    );
    $weight++;
  }

  return $config;
}

/**
 * Helper function. Process hook_entity_view_alter() for product entity, full mode
 *
 * @see xdruple_commerce_entity_view_alter()
 * @see hook_entity_view_alter()
 *
 * @param $build
 */
function _xdruple_commerce_product_entity_view_alter(&$build) {
  $config = xdruple_commerce_get_product_display_config();

  foreach ($build as $key => &$item) {
    if (is_array($item) && !empty($item['#theme']) && $item['#theme'] == 'field') {
      $item['#access'] = false;

      if (!empty($config[$key])) {
        $field_config = $config[$key];

        if (!empty($field_config['title'])) {
          $item['#title'] = t($field_config['title']);
        }

        $item['#label_display'] = $field_config['label'];
        $item['#weight'] = $field_config['weight'];

        $item['#access'] = true;
      }
    }
  }

  // Overriding any current value for xt_url_image_field display
  if (!empty($build['xt_url_image_field']['#items']) && $build['xt_url_image_field']['#access']) {
    $img_field = &$build['xt_url_image_field'];
    $img_field['#formatter'] = 'fancybox';
    foreach ($img_field['#items'] as $i => $item) {
      $img_field[$i] = array(
        '#theme' => 'fancybox_formatter_default',
        '#settings' => array(
          'cyclic' => TRUE,
          'full' => 'large',
          'preview' => 'ft_commerce_product_page_thumb_small',
          'title_position' => 'over',
          'title_show' => TRUE,
        ),
        '#item' => array(
          'path' => $item['uri'],
          'width' => $item['width'],
          'height' => $item['height'],
          'alt' => $item['alt'],
          'title' => $item['title'],
        ),
        '#class' => array('fancybox-commerce-product-product-xt-url-image-field'),
        '#rel' => 'fancybox-commerce-product-product-xt-url-image-field',
      );
    }
  }

  // Overriding default substitutes property to be themed
  if (!empty($build['substitutes']['#items'])) {
    foreach ($build['substitutes']['#items'] as $i => $product_id) {
      $build['substitutes'][$i] = array(
        '#theme' => 'xdruple_commerce_similar_product_link_default',
        '#product_id' => $product_id,
        '#style' => 'ft_commerce_product_thumb',
      );
    }
  }
  else {
    $build['substitutes']['#access'] = FALSE;
  }
}
