<?php

/**
 * Implements hook_cpanel_alter()
 *
 * @param $form
 * @param $form_state
 */
function xdruple_checkout_cpanel_alter(&$form, &$form_state) {
  if (empty($form['xdruple_commerce_store_settings'])) {
    $form['xdruple_commerce_store_settings'] = [
      '#type' => 'fieldset',
      '#title' => t('Store settings'),
      '#group' => 'system_settings',
    ];
  }

  $form['xdruple_commerce_store_settings']['xdruple_checkout_message'] = [
    '#type' => 'textarea',
    '#title' => t('Anonymous user checkout redirect login message'),
    '#description' => t('The message that should be displayed on the login page in the checkout process.'),
    '#default_value' => variable_get('xdruple_checkout_message', t('You need to be logged in to be able to checkout.')),
    '#rows' => 2,
  ];
  $form['xdruple_commerce_store_settings']['xdruple_checkout_anonymous'] = [
    '#type' => 'checkbox',
    '#title' => t('Continue without register'),
    '#description' => t('Allow anonymous checkout. This will also provide an Anonymous Checkout option as an alternative to logging in on the login form when a user has initiated the checkout process.'),
    '#default_value' => variable_get('xdruple_checkout_anonymous', FALSE),
  ];
  $form['xdruple_commerce_store_settings']['xdruple_checkout_guest_customer'] = [
    '#type' => 'textfield',
    '#default_value' => variable_get('xdruple_checkout_guest_customer', ''),
    '#title' => t('Guest Customer'),
    '#description' => t('Enter the Customer Number of the Customer to use for all guest checkout orders. All anonymous guest checkout orders will be created under this Customer in xTuple.'),
    '#required' => TRUE,
  ];
  $form['xdruple_commerce_store_settings']['xdruple_checkout_use_guest_customer_price_schedule'] = [
    '#type' => 'checkbox',
    '#title' => t("Use Guest Customer's price schedule for anonymous users"),
    '#description' => t('When checked, anonymous users will not see the Item List Price. Instead a price quote will be fetched and whatever pricing schedule the Guest Customer above is assigned to will adjust prices accordingly.'),
    '#default_value' => variable_get('xdruple_checkout_use_guest_customer_price_schedule', FALSE),
  ];

  if (variable_get('user_email_verification', TRUE)) {
    $form['xdruple_commerce_store_settings']['xdruple_checkout_reset_password_message'] = [
      '#type' => 'textarea',
      '#title' => t('Reset password checkout redirect message'),
      '#description' => t('The message that should be displayed on the reset password page for new accounts during the checkout process. When an anonymous users checks out and chooses to create a new account, they will be sent a one time login link to their email address. After clicking on it, they will be sent to the Reset Password page to create a password. This message will display on that page so they know they can continue their order after setting a password.'),
      '#default_value' => variable_get('xdruple_checkout_reset_password_message', t('Enter and save a new password and then you can continue with the checkout process.')),
      '#rows' => 2,
    ];
  }
}

/**
 * Implements hook_default_rules_configuration_alter()
 *
 * @param $configs
 */
function xdruple_checkout_default_rules_configuration_alter(&$configs) {
  // Disable Commerce checkout default rules we do not need.
  if (!empty($configs['commerce_checkout_order_convert'])) {
    $configs['commerce_checkout_order_convert']->active = FALSE;
  }
  if (!empty($configs['commerce_checkout_new_account']->active)) {
    $configs['commerce_checkout_new_account']->active = FALSE;
  }
}

/**
 * Implements hook_features_exclude()
 *
 * @return array
 */
function xdruple_checkout_features_exclude() {
  return [
    'variable' => [
      'xdruple_checkout_manager_order_confirm_emails',
      'xdruple_checkout_message',
      'xdruple_checkout_reset_password_message',
    ],
  ];
}
