<?php

/**
 * @file keeps Drupal core hooks implementation
 */

/**
 * Implements hook_menu()
 */
function xdruple_recent_menu() {
  $items = [];

  $items["user/%user/recent"] = [
    "title" => "Recently ordered",
    "page callback" => "xdruple_recent_products_recent_page",
    "page arguments" => [
      "limit" => "20",
    ],
    "access callback" => "xdruple_access",
    "access arguments" => ["products/recent", "view", "xtuple: access product lists"],
    "file" => "pages/products.inc",
    "type" => MENU_LOCAL_TASK,
  ];

  return $items;
}

/**
 * Implements hook_rescued_resources().
 */
function xdruple_recent_rescued_resources() {
  return [
    "XdCatalogRecentOrder",
  ];
}
