<?php

/**
 * @file keep Drupal hooks implementations
 */

/**
 * Implements hook_ctools_plugin_directory()
 */
function xdruple_queries_ctools_plugin_directory($module, $plugin) {
  return "plugins/$plugin";
}

/**
 * Implements hook_init()
 */
function xdruple_queries_init() {
  
}

/**
 * Implements hook_menu()
 */
function xdruple_queries_menu() {
  $items = array();

  return $items;
}

/**
 * Implements hook_theme()
 */
function xdruple_queries_theme() {
  $items = array();

  return $items;
}
