<?php

/**
 * @file keep Drupal hooks implementations
 */

/**
 * Implements hook_ctools_plugin_directory()
 */
function xdruple_queries_ctools_plugin_directory($module, $plugin) {
  return "plugins/$plugin";
}

/**
 * Implements hook_init()
 */
function xdruple_queries_init() {
  module_load_include('inc', 'xdruple_queries', 'pages/categories');
  module_load_include('inc', 'xdruple_queries', 'pages/product');
  module_load_include('inc', 'xdruple_queries', 'pages/products_by_category');
}

/**
 * Implements hook_menu()
 */
function xdruple_queries_menu() {
  $items = array();

  $items['products'] = array(
    'title'            => 'Products',
    'page callback'    => 'xdruple_queries_products_page',
    'page arguments'   => array(1),
    'access arguments' => array('access content'),
    'file'             => 'pages/products.inc',
    'type'             => MENU_NORMAL_ITEM,
  );

  $items['products/list'] = array(
    'title'  => 'Products',
    'type'   => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['products/%'] = array(
    'title'            => 'Product',
    'page callback'    => 'xdruple_queries_product_page',
    'page arguments'   => array(1),
    'access arguments' => array('access content'),
    'file'             => 'pages/product.inc',
    'type'             => MENU_CALLBACK,
  );

  $items['products/categories'] = array(
    'title'            => 'Categories',
    'page callback'    => 'xdruple_queries_categories_page',
    'access arguments' => array('access content'),
    'file'             => 'pages/categories.inc',
    'type'             => MENU_CALLBACK,
  );

  $items['products/categories/%'] = array(
    'title'            => 'Products by category',
    'page callback'    => 'xdruple_queries_products_by_category_page',
    'page arguments'   => array(2),
    'access arguments' => array('access content'),
    'file'             => 'pages/products_by_category.inc',
    'type'             => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function xdruple_queries_theme() {
  $items = array();

  $items['products_page'] = array(
    'variables' => array(
      'products' => array(),
    ),
    'template'  => 'theme/products-page',
    'file'      => 'theme/theme.inc',
  );

  $items['products_page_item'] = array(
    'variables' => array(
      'product' => NULL,
    ),
    'template'  => 'theme/products-page-item',
    'file'      => 'theme/theme.inc',
  );

  return $items;
}
