<?php

/**
 * @file keeps Drupal core hooks implementations
 */

define('XDRUPLE_FAVORITES_ADD', 'add');
define('XDRUPLE_FAVORITES_REMOVE', 'remove');

/**
 * Implements hook_forms()
 *
 * @param $form_id
 *
 * @return array
 */
function xdruple_favorites_forms($form_id) {
  $forms = [];

  if (strpos($form_id, 'xdruple_favorites_add_to_favorites_form_') === 0) {
    $forms[$form_id] = [
      'callback' => 'xdruple_favorites_add_to_favorites_form',
    ];
  }

  if (strpos($form_id, 'xdruple_favorites_remove_from_favorites_form_') === 0) {
    $forms[$form_id] = [
      'callback' => 'xdruple_favorites_remove_from_favorites_form',
    ];
  }

  return $forms;
}

/**
 * Implements hook_init()
 */
function xdruple_favorites_init() {
  module_load_include('inc', 'xdruple_favorites', 'forms/add_to_favorites');
  module_load_include('inc', 'xdruple_favorites', 'forms/remove_from_favorites');
}

/**
 * Implements hook_menu()
 */
function xdruple_favorites_menu() {
  $items = [];

  $items["products/favorites"] = [
    "title" => "Favorite products",
    "title callback" => "xdruple_favorites_favorite_products_page_title",
    "title arguments" => ["xdruple_favorites_favorites_title", "Favorite products"],
    "page callback" => "xdruple_favorites_favorite_products_page",
    "page arguments" => [
      "limit" => "20",
    ],
    "access callback" => "xdruple_access",
    "access arguments" => ["products/favorites", "view", "xtuple: access product lists"],
    "file" => "pages/favorites.inc",
    "type" => MENU_LOCAL_TASK,
  ];

  return $items;
}

/**
 * Implements hook_rescued_resources().
 */
function xdruple_favorites_rescued_resources() {
  return [
    "XdCatalogShipToStandardOrder",
    "XdStandardOrderProduct",
  ];
}

/**
 * Helper function. Returns form array for "add to" or "remove from" Favorites form
 *
 * @param integer $product_id
 * @param         $customer
 * @param         $ship_to
 *
 * @return array
 *
 * @see drupal_get_form()
 */
function xdruple_favorites_get_favorites_form($product_id, $customer, $ship_to) {
  $form_id = _xdruple_favorites_get_favorites_form_id($product_id);

  return drupal_get_form($form_id, $product_id, $customer, $ship_to);
}

/**
 * Helper function. Returns Favorites form ID for "add to" or "remove from" Favorites form.
 *
 * @param integer $product_id
 *
 * @return string
 */
function _xdruple_favorites_get_favorites_form_id($product_id) {
  $form_id = 'xdruple_favorites_add_to_favorites_form_' . $product_id;

  if (in_array($product_id, _xdruple_queries_load_products_by_order_type('xdcatalogshiptostandardorder'))) {
    $form_id = 'xdruple_favorites_remove_from_favorites_form_' . $product_id;
  }

  return $form_id;
}

/**
 * Helper function. Prepares "Add to" and "Remove from" form
 *
 * @param string $op
 * @param        $form
 * @param        $form_state
 * @param        $product_id
 * @param        $customer
 * @param        $ship_to
 *
 * @return mixed
 */
function _xdruple_favorites_prepare_add_remove_form($op = XDRUPLE_FAVORITES_ADD, $form, &$form_state, $product_id, $customer, $ship_to) {
  $title = 'Add to the !favorites';
  $css_id = 'xdruple_favorites_add_to_favorites_form';

  if ($op == XDRUPLE_FAVORITES_REMOVE) {
    $title = 'Remove from the !favorites';
    $css_id = 'xdruple_favorites_remove_from_favorites_form';
  }

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t($title, [
      '!favorites' => t(variable_get('xdruple_favorites_favorites_title', 'Favorite products')),
    ]),
  ];

  $form['product_id'] = [
    '#type' => 'value',
    '#value' => $product_id,
  ];
  $form['customer'] = [
    '#type' => 'value',
    '#value' => $customer,
  ];
  $form['ship_to'] = [
    '#type' => 'value',
    '#value' => $ship_to,
  ];

  if (variable_get('xdruple_favorites_ajax_enabled', TRUE)) {
    $form['submit']['#ajax'] = [
      'callback' => 'xdruple_favorites_favorites_form_submit_ajax',
      'method' => 'replace',
      'prevent' => 'click',
    ];
    $form['#page_url'] = $_GET['q'];
  }

  $form['#attributes']['class'][] = drupal_clean_css_identifier($css_id);

  return $form;
}

/**
 * AJAX callback. Processes "Add to" and "Remove from" form submissions
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function xdruple_favorites_favorites_form_submit_ajax($form, $form_state) {
  $commands = [];

  /** @var Xtuple\Xdruple\Session\RescuedSession $session */
  global $session;

  if (($customer = $session->getRescued('customer'))
    && ($ship_to = $session->getRescued('ship_to'))
  ) {
    $product_id = $form_state['values']['product_id'];
    $replace_id = $form['#id'];
    $new_form = xdruple_favorites_get_favorites_form($product_id, $customer, $ship_to);
    $commands['replace'] = ajax_command_replace("#$replace_id", drupal_render($new_form));
  }
  $commands['messages'] = ajax_command_insert('#status-messages', theme('status_messages'));

  drupal_alter('xdruple_favorites_favorites_form_submit_ajax_commands', $commands, $form, $form_state, $new_form);

  return [
    '#type' => 'ajax',
    '#commands' => $commands,
  ];
}

function xdruple_favorites_favorite_products_page_title($variable, $default) {
  return t(variable_get($variable, $default));
}

/**
 * Implements hook_preprocess_xdruple_product_page().
 *
 * @param $variables
 */
function xdruple_favorites_preprocess_xdruple_product_page(&$variables) {
  if (!empty($variables["product"])) {
    /** @var \Xtuple\Rescued\Controller\Entity $product */
    $product = $variables["product"];
    if (empty($product->get("event"))) {
      if (($customer = xdruple_rescued_session_get("customer"))
        && ($ship_to = xdruple_rescued_session_get("ship_to"))
      ) {
        $form = xdruple_favorites_get_favorites_form($product->getId(), $customer, $ship_to);
        $variables["actions"]["add_to_standard"] = [
          "#markup" => drupal_render($form),
          "#weight" => 20,
        ];
      }
    }
  }
}

/**
 * Implements hook_preprocess_xdruple_event_purchase()
 * 
 * @param $variables
 */
function xdruple_favorites_preprocess_xdruple_event_purchase(&$variables) {
  /** @var \Xtuple\Rescued\Controller\Entity $product */
  $product = $variables["product"];
  if (($customer = xdruple_rescued_session_get("customer"))
    && ($ship_to = xdruple_rescued_session_get("ship_to"))
  ) {
    $form = xdruple_favorites_get_favorites_form($product->getId(), $customer, $ship_to);
    $variables["purchase"]["add_to_standard"] = [
      "#markup" => drupal_render($form),
      "#weight" => 20,
    ];
  }
}

/**
 * @param $variables
 */
function xdruple_favorites_preprocess_xdruple_products_table(&$variables) {
  if (($customer = xdruple_rescued_session_get("customer"))
    && ($ship_to = xdruple_rescued_session_get("ship_to"))
  ) {
    $variables["header"]["favorite"] = [
      "data" => t("Favorite"),
      "class" => [
        "favorite" => "favorite",
        "no-wrap" => "no-wrap",
      ],
      "weight" => 20,
    ];
    if (!empty($variables["rows"])) {
      foreach ($variables["rows"] as $key => &$row) {
        /** @var \Xtuple\Rescued\Controller\Entity $product */
        $product = $variables["products"][$key];
        $form = xdruple_favorites_get_favorites_form($product->get("product_id"), $customer, $ship_to);
        $row["favorite"] = [
          "data" => drupal_render($form),
        ];
      }
    }
  }
}
