<?php

/**
 * @file
 * Create a Drupal Commerce Speciality Shipping Service
 */

/**
 * Implements hook_menu().
 */
function xdruple_speciality_shipping_menu() {
  // xDruple Commerce Speciality Shipping Service settings page.
  $items['admin/commerce/config/shipping/methods/xdruple_speciality_shipping/edit'] = array(
    'title' => 'Edit',
    'description' => 'xDruple Commerce Speciality Shipping Service method settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xdruple_speciality_shipping_settings_form'),
    'access arguments' => array('administer shipping'),
    'file' => 'xdruple_speciality_shipping.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 0,
  );

  return $items;
}

/**
 * Implements hook_commerce_shipping_method_info().
 */
function xdruple_speciality_shipping_commerce_shipping_method_info() {
  $shipping_methods = array();

  $shipping_methods['xdruple_speciality_shipping'] = array(
    'title' => t('Speciality Shipping Service'),
    'description' => t('Allows you to define Speciality Shipping Service for customers to choose during checkout.'),
  );

  return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function xdruple_speciality_shipping_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['xdruple_speciality_shipping'] = array(
    'title' => t('Speciality Shipping Service'),
    'description' => t('One of our representatives will be in touch with you to arrange shipping after your order is placed.'),
    'display_title' => t('Request Speciality Shipping Service'),
    'shipping_method' => 'xdruple_speciality_shipping',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'xdruple_speciality_shipping_service_rate',
    )
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function xdruple_speciality_shipping_service_rate($shipping_service, $order) {
  return array(
    'amount' => variable_get('xdruple_speciality_shipping_service_amount', 0) * 100,
    'currency_code' => commerce_default_currency(),
    'data' => array(),
  );
}
