<?php

/**
 * Implements hook_views_api().
 */
function xdruple_order_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'xdruple_order') . '/includes/views',
  );
}

/**
 * Implements hook_init()
 */
function xdruple_order_init() {
  module_load_include('inc', 'xdruple_order', 'pages/invoice');
}

/**
 * Implements hook_menu()
 */
function xdruple_order_menu() {
  $items = array();

  $items['order/%'] = array(
    'title'            => 'Order',
    'page callback'    => 'xdruple_order_page',
    'page arguments'   => array(1),
    'access arguments' => array('access content'),
    'file'             => 'pages/order.inc',
    'type'             => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_views_pre_execute().
 */
function xdruple_order_views_pre_execute($view) {
  if ($view->name === 'xd_pending_orders') {
    // Query on Customer.
    if (isset($_SESSION['rescued']['customer'])) {
      $view->query->query->propertyConditions[] = array(
        'column' => 'customer',
        'value' => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
      $view->build_info['count_query']->propertyConditions[] = array(
        'column' => 'customer',
        'value' => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
    }

    // Query on Ship To.
    if (isset($_SESSION['rescued']['ship_to'])) {
      // Get the Ship To Name.
      $shipto_name = entity_load_single('xtuple_xdruplecommerceshipto', $_SESSION['rescued']['ship_to']);

      $view->query->query->propertyConditions[] = array(
        'column' => 'shiptoName',
        'value' => $shipto_name->name,
        'operator' => '=',
      );
      $view->build_info['count_query']->propertyConditions[] = array(
        'column' => 'shiptoName',
        'value' => $shipto_name->name,
        'operator' => '=',
      );
    }
  }
}

/**
 * Implements hook_theme()
 */
function xdruple_order_theme() {
  $items = array();

  $items['order_page'] = array(
    'variables' => array(
      'order' => array(),
    ),
    'template'  => 'theme/order-page',
    'file'      => 'theme/theme.inc',
  );

  return $items;
}
