<?php

include_once __DIR__ . '/pages/order.inc';

/**
 * Implements hook_views_api().
 */
function xdruple_order_views_api() {
  return array(
    'api'  => 3,
    'path' => drupal_get_path('module', 'xdruple_order') . '/includes/views',
  );
}

/**
 * Implements hook_init()
 */
function xdruple_order_init() {
}

/**
 * Implements hook_menu()
 */
function xdruple_order_menu() {
  $items = array();

  $items['user/%user/pending-orders/%'] = array(
    'title'            => 'Order',
    'title callback'   => 'xdruple_order_page_title',
    'title arguments'  => array(3),
    'page callback'    => 'xdruple_order_page',
    'page arguments'   => array(3),
    'access arguments' => array('access content'),
    'file'             => 'pages/order.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_get_item_alter()
 */
function xdruple_order_menu_get_item_alter(&$router_item) {
  if ($router_item['path'] == 'user/%/pending-orders/%') {
    $router_item['tab_parent'] = 'user/%';
    $router_item['tab_root']   = 'user/%';
    $router_item['type']       = "132";
    $router_item['context']    = 1;
  }
}

/**
 * Implements hook_rescued_register_clients_resources_alter().
 */
function xdruple_order_rescued_register_clients_resources_alter(&$rescued_clients_url_resources) {
  if (!in_array('SalesOrder', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'SalesOrder';
  }
  if (!in_array('SalesOrderListItem', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'SalesOrderListItem';
  }
  if (!in_array('RemitTo', $rescued_clients_url_resources['xtuple'])) {
    $rescued_clients_url_resources['xtuple'][] = 'RemitTo';
  }

  return $rescued_clients_url_resources;
}

/**
 * Implements hook_views_pre_execute().
 */
function xdruple_order_views_pre_execute($view) {
  if ($view->name === 'xd_pending_orders') {
    // Query on Customer.
    if (isset($_SESSION['rescued']['customer'])) {
      $view->query->query->propertyConditions[]              = array(
        'column'   => 'customer',
        'value'    => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
      $view->build_info['count_query']->propertyConditions[] = array(
        'column'   => 'customer',
        'value'    => $_SESSION['rescued']['customer'],
        'operator' => '=',
      );
    }

    // Query on Ship To.
    if (isset($_SESSION['rescued']['ship_to'])) {
      // Get the Ship To Name.
      $shipto_name = entity_load_single('xtuple_xdruplecommerceshipto', $_SESSION['rescued']['ship_to']);

      $view->query->query->propertyConditions[]              = array(
        'column'   => 'shiptoName',
        'value'    => $shipto_name->name,
        'operator' => '=',
      );
      $view->build_info['count_query']->propertyConditions[] = array(
        'column'   => 'shiptoName',
        'value'    => $shipto_name->name,
        'operator' => '=',
      );
    }
  }
}

/**
 * Implements hook_theme()
 */
function xdruple_order_theme() {
  $items = array();

  $items['order_page'] = array(
    'variables' => array(
      'order' => array(),
    ),
    'template'  => 'theme/order-page',
    'file'      => 'theme/theme.inc',
  );

  return $items;
}
