<?php

/**
 * Implements hook_menu().
 */
function xdruple_catalog_menu() {
  $items = array();

  // Add a base menu item for the product catalog.
  $items['products2'] = array(
    'page callback' => 'xdruple_catalog_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Render the filtered list of products.
 * @param integer $group_id
 */
function xdruple_catalog_page($group_id) {
  $conditions = array(
    'parentGroup' => $group_id
  );

  // Example using entity_load();
  $group_products = entity_load('xtuple_xdrupleitemgroupitem', null, $conditions);
  foreach ($group_products as $item) {
    //$product_entity = entity_load('xtuple_xdruplecommerceproduct', array($product->Product));

    $product_entity = entity_load_single('commerce_product', $item->Product);
    $product_ids = array($product_entity->product_id);
    $line_item = commerce_product_line_item_new($product_entity, 1, 0, array(), null);
    $line_item->data['context']['product_ids'] = $product_ids;
    $line_item->data['context']['add_to_cart_combine'] = true;

    // Generate a form ID for this add to cart form.
    $form_id = commerce_cart_add_to_cart_form_id($product_ids);

    // Build the Add to Cart form using the prepared values.
    $form = drupal_get_form($form_id, $line_item, true, array());

    // TODO: Aggrigate for all products, not just one loop.
    return drupal_render($form);
  }
}
